// Math — Algebra
// Skills: linear equations, linear functions, systems of equations, inequalities
// All content is original, written for this practice site.

QUESTIONS.push(
  {
    id: "alg-1",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 1,
    prompt: "If 4x − 9 = 23, what is the value of x?",
    choices: ["8", "6", "3.5", "32"],
    answer: 0,
    explanation: "4x − 9 = 23 → 4x = 32 → x = 8.",
  },
  {
    id: "alg-2",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 1,
    prompt: "If 2(x + 3) = 5x − 6, what is the value of x?",
    choices: ["4", "2", "6", "−4"],
    answer: 0,
    explanation: "2x + 6 = 5x − 6 → 12 = 3x → x = 4.",
  },
  {
    id: "alg-3",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "A line passes through the points (2, 5) and (4, 11). What is the y-intercept of the line?",
    choices: ["−1", "1", "5", "11"],
    answer: 0,
    explanation:
      "Slope = (11 − 5)/(4 − 2) = 3. Using y = 3x + b with (2, 5): 5 = 3(2) + b → b = −1.",
  },
  {
    id: "alg-4",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 1,
    prompt: "If x + y = 10 and x − y = 2, what is the value of y?",
    choices: ["4", "6", "8", "2"],
    answer: 0,
    explanation: "Subtract the equations: (x + y) − (x − y) = 10 − 2 → 2y = 8 → y = 4.",
  },
  {
    id: "alg-5",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 1,
    prompt: "What is the smallest integer value of x that satisfies 3x − 5 > 10?",
    choices: ["6", "5", "4", "15"],
    answer: 0,
    explanation: "3x − 5 > 10 → 3x > 15 → x > 5, so the smallest integer satisfying this is 6.",
  },
  {
    id: "alg-6",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt:
      "A gym membership costs $25 to join plus $15 per month. If a member has paid a total of $205, how many months has the membership been active?",
    choices: ["12", "10", "13", "180"],
    answer: 0,
    explanation: "25 + 15m = 205 → 15m = 180 → m = 12.",
  },
  {
    id: "alg-7",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt: "If y = 2x − 1 and 3x + y = 14, what is the value of x + y?",
    choices: ["8", "3", "5", "11"],
    answer: 0,
    explanation:
      "Substitute: 3x + (2x − 1) = 14 → 5x = 15 → x = 3, so y = 2(3) − 1 = 5. Thus x + y = 8.",
  },
  {
    id: "alg-8",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "The function f is linear, with f(0) = 4 and f(2) = 10. What is the value of f(5)?",
    choices: ["19", "14", "10", "25"],
    answer: 0,
    explanation:
      "Slope = (10 − 4)/(2 − 0) = 3, so f(x) = 3x + 4. Then f(5) = 3(5) + 4 = 19.",
  },
  {
    id: "alg-9",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt:
      "A line given by y = 2x + 3 is parallel to a second line that passes through (0, −1). What is the slope of the second line?",
    choices: ["2", "−1", "3", "1/2"],
    answer: 0,
    explanation: "Parallel lines have equal slopes, so the second line also has slope 2.",
  },
  {
    id: "alg-10",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt: "If |x − 4| = 9, what is the sum of all possible values of x?",
    choices: ["8", "9", "−5", "13"],
    answer: 0,
    explanation:
      "x − 4 = 9 gives x = 13; x − 4 = −9 gives x = −5. The sum of the two solutions is 13 + (−5) = 8.",
  },
  {
    id: "alg-11",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt: "How many solutions does the system y = 2x + 5 and y = 2x + 3 have?",
    choices: ["0", "1", "2", "Infinitely many"],
    answer: 0,
    explanation:
      "Setting the equations equal: 2x + 5 = 2x + 3 → 5 = 3, which is false. The lines are parallel with different intercepts, so there is no solution.",
  },
  {
    id: "alg-12",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt:
      "A parking garage charges $5 for the first hour and $2 for each additional hour. What is the maximum number of whole hours a driver can park without exceeding $19?",
    choices: ["8", "7", "9", "10"],
    answer: 0,
    explanation:
      "5 + 2(h − 1) ≤ 19 → 2(h − 1) ≤ 14 → h − 1 ≤ 7 → h ≤ 8, so the maximum is 8 hours.",
  },
  {
    id: "alg-13",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt: "What is the slope of the line given by 3x + 2y = 12?",
    choices: ["−3/2", "3/2", "2/3", "−2/3"],
    answer: 0,
    explanation: "Solving for y: 2y = −3x + 12 → y = (−3/2)x + 6, so the slope is −3/2.",
  },
  {
    id: "alg-14",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt: "What is the x-intercept of the line 2x − 5y = 20?",
    choices: ["10", "−4", "4", "−10"],
    answer: 0,
    explanation: "Set y = 0: 2x = 20 → x = 10.",
  },
  {
    id: "alg-15",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 1,
    prompt: "If 3x − y = 7 and x + y = 9, what is the value of y?",
    choices: ["5", "4", "9", "7"],
    answer: 0,
    explanation: "Adding the equations: 4x = 16 → x = 4. Then from x + y = 9, y = 5.",
  },
  {
    id: "alg-16",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt:
      "A cell phone plan costs $20 plus $0.10 per minute of calls. If a customer's bill was $35, how many minutes of calls were made?",
    choices: ["150", "15", "175", "350"],
    answer: 0,
    explanation: "20 + 0.10m = 35 → 0.10m = 15 → m = 150.",
  },
  {
    id: "alg-17",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt:
      "Company A charges $50 plus $3 per unit produced. Company B charges $20 plus $5 per unit produced. For what number of units is the total cost the same for both companies?",
    choices: ["15", "10", "30", "6"],
    answer: 0,
    explanation: "50 + 3x = 20 + 5x → 30 = 2x → x = 15.",
  },
  {
    id: "alg-18",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt: "What is the greatest integer value of x that satisfies −3 < 2x + 1 ≤ 7?",
    choices: ["3", "2", "−2", "−1"],
    answer: 0,
    explanation: "−4 < 2x ≤ 6 → −2 < x ≤ 3, so the greatest integer value is 3.",
  },
  {
    id: "alg-19",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 3,
    prompt: "The formula A = P(1 + rt) can be solved for r in terms of A, P, and t. Which expression is equivalent to r?",
    choices: ["(A − P)/(Pt)", "(A − Pt)/P", "A/(Pt) − 1", "(A − P)/t"],
    answer: 0,
    explanation:
      "A = P + Prt → A − P = Prt → r = (A − P)/(Pt).",
  },
  {
    id: "alg-20",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt:
      "Sarah is 4 years older than twice Tom's age. If Sarah is 22 years old, how old is Tom?",
    choices: ["9", "11", "18", "13"],
    answer: 0,
    explanation: "22 = 2t + 4 → 18 = 2t → t = 9.",
  },
  {
    id: "alg-21",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt:
      "A water tank had 80 gallons at time t = 0 and 20 gallons at t = 6 minutes, draining at a constant rate. What is the drain rate in gallons per minute?",
    choices: ["10", "60", "6", "600"],
    answer: 0,
    explanation: "The tank lost 60 gallons over 6 minutes: 60/6 = 10 gallons per minute.",
  },
  {
    id: "alg-22",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt: "How many solutions does the system 6x − 2y = 10 and y = 3x − 5 have?",
    choices: ["Infinitely many", "0", "Exactly 1", "Exactly 2"],
    answer: 0,
    explanation:
      "Substituting: 6x − 2(3x − 5) = 10 → 6x − 6x + 10 = 10 → 10 = 10, which is always true, so the system has infinitely many solutions.",
  },
  {
    id: "alg-23",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in two variables",
    difficulty: 2,
    prompt: "Which ordered pair is a solution to the inequality y ≤ 3x − 2?",
    choices: ["(2, 3)", "(0, 0)", "(−1, 2)", "(1, 5)"],
    answer: 0,
    explanation:
      "For (2, 3): 3 ≤ 3(2) − 2 = 4, which is true. The other points fail the inequality when checked.",
  },
  {
    id: "alg-24",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "A line has a slope of −3 and passes through (1, 2). What is the value of y when x = 4?",
    choices: ["−7", "−10", "7", "−1"],
    answer: 0,
    explanation: "y − 2 = −3(x − 1) → y = −3x + 5. At x = 4: y = −12 + 5 = −7.",
  },
  {
    id: "alg-25",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt:
      "Adult movie tickets cost $12 and child tickets cost $8. A group bought 5 tickets for a total of $52. How many adult tickets were purchased?",
    choices: ["3", "2", "4", "5"],
    answer: 0,
    explanation:
      "Let a + c = 5 and 12a + 8c = 52. Substituting c = 5 − a: 12a + 8(5 − a) = 52 → 4a = 12 → a = 3.",
  }
);
