// Math — Algebra
// Skills: linear equations, linear functions, systems of equations, inequalities
// All content is original, written for this practice site.

QUESTIONS.push(
  {
    id: "alg-1",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 1,
    prompt: "If 4x − 9 = 23, what is the value of x?",
    choices: ["8", "6", "3.5", "32"],
    answer: 0,
    explanation: "4x − 9 = 23 → 4x = 32 → x = 8.",
  },
  {
    id: "alg-2",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 1,
    prompt: "If 2(x + 3) = 5x − 6, what is the value of x?",
    choices: ["4", "2", "6", "−4"],
    answer: 0,
    explanation: "2x + 6 = 5x − 6 → 12 = 3x → x = 4.",
  },
  {
    id: "alg-3",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "A line passes through the points (2, 5) and (4, 11). What is the y-intercept of the line?",
    choices: ["−1", "1", "5", "11"],
    answer: 0,
    explanation:
      "Slope = (11 − 5)/(4 − 2) = 3. Using y = 3x + b with (2, 5): 5 = 3(2) + b → b = −1.",
  },
  {
    id: "alg-4",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 1,
    prompt: "If x + y = 10 and x − y = 2, what is the value of y?",
    choices: ["4", "6", "8", "2"],
    answer: 0,
    explanation: "Subtract the equations: (x + y) − (x − y) = 10 − 2 → 2y = 8 → y = 4.",
  },
  {
    id: "alg-5",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 1,
    prompt: "What is the smallest integer value of x that satisfies 3x − 5 > 10?",
    choices: ["6", "5", "4", "15"],
    answer: 0,
    explanation: "3x − 5 > 10 → 3x > 15 → x > 5, so the smallest integer satisfying this is 6.",
  },
  {
    id: "alg-6",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt:
      "A gym membership costs $25 to join plus $15 per month. If a member has paid a total of $205, how many months has the membership been active?",
    choices: ["12", "10", "13", "180"],
    answer: 0,
    explanation: "25 + 15m = 205 → 15m = 180 → m = 12.",
  },
  {
    id: "alg-7",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt: "If y = 2x − 1 and 3x + y = 14, what is the value of x + y?",
    choices: ["8", "3", "5", "11"],
    answer: 0,
    explanation:
      "Substitute: 3x + (2x − 1) = 14 → 5x = 15 → x = 3, so y = 2(3) − 1 = 5. Thus x + y = 8.",
  },
  {
    id: "alg-8",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "The function f is linear, with f(0) = 4 and f(2) = 10. What is the value of f(5)?",
    choices: ["19", "14", "10", "25"],
    answer: 0,
    explanation:
      "Slope = (10 − 4)/(2 − 0) = 3, so f(x) = 3x + 4. Then f(5) = 3(5) + 4 = 19.",
  },
  {
    id: "alg-9",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt:
      "A line given by y = 2x + 3 is parallel to a second line that passes through (0, −1). What is the slope of the second line?",
    choices: ["2", "−1", "3", "1/2"],
    answer: 0,
    explanation: "Parallel lines have equal slopes, so the second line also has slope 2.",
  },
  {
    id: "alg-10",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt: "If |x − 4| = 9, what is the sum of all possible values of x?",
    choices: ["8", "9", "−5", "13"],
    answer: 0,
    explanation:
      "x − 4 = 9 gives x = 13; x − 4 = −9 gives x = −5. The sum of the two solutions is 13 + (−5) = 8.",
  },
  {
    id: "alg-11",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt: "How many solutions does the system y = 2x + 5 and y = 2x + 3 have?",
    choices: ["0", "1", "2", "Infinitely many"],
    answer: 0,
    explanation:
      "Setting the equations equal: 2x + 5 = 2x + 3 → 5 = 3, which is false. The lines are parallel with different intercepts, so there is no solution.",
  },
  {
    id: "alg-12",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt:
      "A parking garage charges $5 for the first hour and $2 for each additional hour. What is the maximum number of whole hours a driver can park without exceeding $19?",
    choices: ["8", "7", "9", "10"],
    answer: 0,
    explanation:
      "5 + 2(h − 1) ≤ 19 → 2(h − 1) ≤ 14 → h − 1 ≤ 7 → h ≤ 8, so the maximum is 8 hours.",
  },
  {
    id: "alg-13",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt: "What is the slope of the line given by 3x + 2y = 12?",
    choices: ["−3/2", "3/2", "2/3", "−2/3"],
    answer: 0,
    explanation: "Solving for y: 2y = −3x + 12 → y = (−3/2)x + 6, so the slope is −3/2.",
  },
  {
    id: "alg-14",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt: "What is the x-intercept of the line 2x − 5y = 20?",
    choices: ["10", "−4", "4", "−10"],
    answer: 0,
    explanation: "Set y = 0: 2x = 20 → x = 10.",
  },
  {
    id: "alg-15",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 1,
    prompt: "If 3x − y = 7 and x + y = 9, what is the value of y?",
    choices: ["5", "4", "9", "7"],
    answer: 0,
    explanation: "Adding the equations: 4x = 16 → x = 4. Then from x + y = 9, y = 5.",
  },
  {
    id: "alg-16",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt:
      "A cell phone plan costs $20 plus $0.10 per minute of calls. If a customer's bill was $35, how many minutes of calls were made?",
    choices: ["150", "15", "175", "350"],
    answer: 0,
    explanation: "20 + 0.10m = 35 → 0.10m = 15 → m = 150.",
  },
  {
    id: "alg-17",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt:
      "Company A charges $50 plus $3 per unit produced. Company B charges $20 plus $5 per unit produced. For what number of units is the total cost the same for both companies?",
    choices: ["15", "10", "30", "6"],
    answer: 0,
    explanation: "50 + 3x = 20 + 5x → 30 = 2x → x = 15.",
  },
  {
    id: "alg-18",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt: "What is the greatest integer value of x that satisfies −3 < 2x + 1 ≤ 7?",
    choices: ["3", "2", "−2", "−1"],
    answer: 0,
    explanation: "−4 < 2x ≤ 6 → −2 < x ≤ 3, so the greatest integer value is 3.",
  },
  {
    id: "alg-19",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 3,
    prompt: "The formula A = P(1 + rt) can be solved for r in terms of A, P, and t. Which expression is equivalent to r?",
    choices: ["(A − P)/(Pt)", "(A − Pt)/P", "A/(Pt) − 1", "(A − P)/t"],
    answer: 0,
    explanation:
      "A = P + Prt → A − P = Prt → r = (A − P)/(Pt).",
  },
  {
    id: "alg-20",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt:
      "Sarah is 4 years older than twice Tom's age. If Sarah is 22 years old, how old is Tom?",
    choices: ["9", "11", "18", "13"],
    answer: 0,
    explanation: "22 = 2t + 4 → 18 = 2t → t = 9.",
  },
  {
    id: "alg-21",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt:
      "A water tank had 80 gallons at time t = 0 and 20 gallons at t = 6 minutes, draining at a constant rate. What is the drain rate in gallons per minute?",
    choices: ["10", "60", "6", "600"],
    answer: 0,
    explanation: "The tank lost 60 gallons over 6 minutes: 60/6 = 10 gallons per minute.",
  },
  {
    id: "alg-22",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt: "How many solutions does the system 6x − 2y = 10 and y = 3x − 5 have?",
    choices: ["Infinitely many", "0", "Exactly 1", "Exactly 2"],
    answer: 0,
    explanation:
      "Substituting: 6x − 2(3x − 5) = 10 → 6x − 6x + 10 = 10 → 10 = 10, which is always true, so the system has infinitely many solutions.",
  },
  {
    id: "alg-23",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in two variables",
    difficulty: 2,
    prompt: "Which ordered pair is a solution to the inequality y ≤ 3x − 2?",
    choices: ["(2, 3)", "(0, 0)", "(−1, 2)", "(1, 5)"],
    answer: 0,
    explanation:
      "For (2, 3): 3 ≤ 3(2) − 2 = 4, which is true. The other points fail the inequality when checked.",
  },
  {
    id: "alg-24",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "A line has a slope of −3 and passes through (1, 2). What is the value of y when x = 4?",
    choices: ["−7", "−10", "7", "−1"],
    answer: 0,
    explanation: "y − 2 = −3(x − 1) → y = −3x + 5. At x = 4: y = −12 + 5 = −7.",
  },
  {
    id: "alg-25",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt:
      "Adult movie tickets cost $12 and child tickets cost $8. A group bought 5 tickets for a total of $52. How many adult tickets were purchased?",
    choices: ["3", "2", "4", "5"],
    answer: 0,
    explanation:
      "Let a + c = 5 and 12a + 8c = 52. Substituting c = 5 − a: 12a + 8(5 − a) = 52 → 4a = 12 → a = 3.",
  },
  {
    id: "alg-26",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt: "If 3x − 2y = 12 and x + y = 9, what is the value of xy?",
    choices: ["18", "27", "15", "12"],
    answer: 0,
    explanation:
      "From x + y = 9, y = 9 − x. Substituting: 3x − 2(9 − x) = 12 → 5x = 30 → x = 6, so y = 3. Then xy = 18.",
  },
  {
    id: "alg-27",
    module: "math",
    domain: "Algebra",
    skill: "Word problems",
    difficulty: 3,
    prompt:
      "The sum of two numbers is 42. The larger number is 2 more than 3 times the smaller number. What is the larger number?",
    choices: ["32", "10", "36", "28"],
    answer: 0,
    explanation:
      "Let the smaller number be x, so the larger is 3x + 2. Then x + (3x + 2) = 42 → 4x = 40 → x = 10, and the larger number is 3(10) + 2 = 32.",
  },
  {
    id: "alg-28",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 3,
    prompt:
      "A phone plan charges a flat monthly fee plus a constant rate per minute of calls. A 40-minute call costs $14, and a 70-minute call costs $20. What is the flat monthly fee?",
    choices: ["$6", "$8", "$4", "$10"],
    answer: 0,
    explanation:
      "The rate per minute is (20 − 14)/(70 − 40) = 6/30 = $0.20. Using the 40-minute call: 14 = fee + 0.20(40) = fee + 8, so the fee is $6.",
  },
  {
    id: "alg-29",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in two variables",
    difficulty: 2,
    prompt: "If 2x + 3y ≤ 18 and x = 3, what is the maximum possible value of y?",
    choices: ["4", "6", "3", "5"],
    answer: 0,
    explanation: "Substituting x = 3: 6 + 3y ≤ 18 → 3y ≤ 12 → y ≤ 4, so the maximum value of y is 4.",
  },
  {
    id: "alg-30",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt:
      "For what value of k does the system of equations 2x + 3y = 6 and 4x + ky = 10 have no solution?",
    choices: ["6", "5", "8", "12"],
    answer: 0,
    explanation:
      "A system has no solution when the lines are parallel but distinct: the coefficient ratios must match while the constant ratio differs. Setting 2/4 = 3/k gives k = 6; since 6/10 ≠ 2/4, the lines are parallel and distinct.",
  },
  {
    id: "alg-31",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 2,
    prompt: "The equation 5x − 2y = 20 is graphed in the xy-plane. What is the x-intercept of the graph?",
    choices: ["4", "10", "−4", "20"],
    answer: 0,
    explanation: "The x-intercept occurs where y = 0: 5x = 20 → x = 4.",
  },
  {
    id: "alg-32",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt: "What is the largest integer value of x that satisfies −4x + 9 > −11?",
    choices: ["4", "5", "3", "−4"],
    answer: 0,
    explanation:
      "−4x + 9 > −11 → −4x > −20 → x < 5 (the inequality flips when dividing by a negative number). The largest integer less than 5 is 4.",
  },
  {
    id: "alg-33",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 3,
    prompt: "Line ℓ has an x-intercept of 4 and a y-intercept of −8. What is the slope of line ℓ?",
    choices: ["2", "−2", "1/2", "−1/2"],
    answer: 0,
    explanation:
      "The line passes through (4, 0) and (0, −8). Slope = (0 − (−8)) / (4 − 0) = 8/4 = 2.",
  },
  {
    id: "alg-34",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 1,
    prompt: "If 5x + 7 = 32, what is the value of x?",
    choices: ["5", "3", "7", "25"],
    answer: 0,
    explanation: "5x + 7 = 32 → 5x = 25 → x = 5.",
  },
  {
    id: "alg-35",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 2,
    prompt:
      "The equation for converting Celsius to Fahrenheit is F = (9/5)C + 32. Which expression gives C in terms of F?",
    choices: ["(5/9)(F − 32)", "(9/5)(F − 32)", "(5/9)F − 32", "(5/9)F + 32"],
    answer: 0,
    explanation: "F − 32 = (9/5)C → C = (5/9)(F − 32).",
  },
  {
    id: "alg-36",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 3,
    prompt:
      "The function g is linear. The table shows g(1) = 7 and g(4) = 19. What is g(10)?",
    choices: ["43", "40", "46", "37"],
    answer: 0,
    explanation:
      "Slope = (19 − 7)/(4 − 1) = 4, so g(x) = 4x + 3. Then g(10) = 4(10) + 3 = 43.",
  },
  {
    id: "alg-37",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 1,
    prompt: "If 2x + y = 15 and y = x − 3, what is the value of x?",
    choices: ["6", "3", "9", "5"],
    answer: 0,
    explanation:
      "Substitute y = x − 3 into 2x + y = 15: 2x + (x − 3) = 15 → 3x = 18 → x = 6.",
  },
  {
    id: "alg-38",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt:
      "A vendor sells popcorn bags for $4 each after paying a $30 booth fee. What is the minimum number of bags the vendor must sell to make a profit greater than $50?",
    choices: ["21", "20", "19", "30"],
    answer: 0,
    explanation:
      "4n − 30 > 50 → 4n > 80 → n > 20, so the minimum whole number of bags is 21.",
  },
  {
    id: "alg-39",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in two variables",
    difficulty: 3,
    prompt:
      "Which of the following ordered pairs is NOT a solution to the inequality 4x − 3y > 12?",
    choices: ["(0, 0)", "(5, 2)", "(6, 0)", "(10, 5)"],
    answer: 0,
    explanation:
      "Testing (0, 0): 4(0) − 3(0) = 0, which is not greater than 12, so (0, 0) is not a solution. The other points each satisfy the inequality: for example, 4(5) − 3(2) = 14 > 12.",
  },
  {
    id: "alg-40",
    module: "math",
    domain: "Algebra",
    skill: "Word problems",
    difficulty: 1,
    prompt:
      "A taxi charges a $3 flat fee plus $2.50 per mile. If a ride costs $15.50, how many miles was the ride?",
    choices: ["5", "6", "4", "12.5"],
    answer: 0,
    explanation: "3 + 2.5m = 15.5 → 2.5m = 12.5 → m = 5.",
  },
  {
    id: "alg-41",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 2,
    prompt: "If (2/3)(x − 6) = 10, what is the value of x?",
    choices: ["21", "9", "6", "15"],
    answer: 0,
    explanation: "(2/3)(x − 6) = 10 → x − 6 = 15 → x = 21.",
  },
  {
    id: "alg-42",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 3,
    prompt:
      "The equation for the perimeter of a rectangle is P = 2l + 2w. Which expression gives w in terms of P and l?",
    choices: ["(P − 2l)/2", "(P − l)/2", "P − 2l", "(P + 2l)/2"],
    answer: 0,
    explanation: "P = 2l + 2w → 2w = P − 2l → w = (P − 2l)/2.",
  },
  {
    id: "alg-43",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 1,
    prompt:
      "A line has a slope of 4 and passes through the point (0, −3). What is the equation of the line?",
    choices: ["y = 4x − 3", "y = 4x + 3", "y = −3x + 4", "y = 4x"],
    answer: 0,
    explanation:
      "Using slope-intercept form y = mx + b with m = 4 and y-intercept b = −3 (from the point (0, −3)): y = 4x − 3.",
  },
  {
    id: "alg-44",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 2,
    prompt:
      "A store sells pens for $2 and notebooks for $5. Maria bought a total of 8 items for $25. How many notebooks did she buy?",
    choices: ["3", "5", "2", "4"],
    answer: 0,
    explanation:
      "Let p + n = 8 and 2p + 5n = 25. Substituting p = 8 − n: 2(8 − n) + 5n = 25 → 16 + 3n = 25 → n = 3.",
  },
  {
    id: "alg-45",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 3,
    prompt:
      "For which value of x is the inequality 5 − 2x ≥ 3x − 10 NOT satisfied?",
    choices: ["4", "3", "0", "−2"],
    answer: 0,
    explanation:
      "Solve the inequality: 5 − 2x ≥ 3x − 10 → 15 ≥ 5x → x ≤ 3. Since 4 > 3, x = 4 does not satisfy the inequality, while the other values do.",
  },
  {
    id: "alg-46",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in two variables",
    difficulty: 1,
    prompt: "Which ordered pair is a solution to the inequality y > x + 1?",
    choices: ["(2, 5)", "(2, 3)", "(0, −1)", "(3, 2)"],
    answer: 0,
    explanation:
      "For (2, 5): 5 > 2 + 1 = 3, which is true. The other points fail the inequality when substituted.",
  },
  {
    id: "alg-47",
    module: "math",
    domain: "Algebra",
    skill: "Word problems",
    difficulty: 2,
    prompt:
      "A tank initially contains 15 gallons of water and is being filled at a rate of 4 gallons per minute. How many minutes will it take for the tank to contain 75 gallons?",
    choices: ["15", "20", "12", "60"],
    answer: 0,
    explanation: "15 + 4m = 75 → 4m = 60 → m = 15.",
  },
  {
    id: "alg-48",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 3,
    prompt: "If 3(2x − 1) − 4(x + 2) = 15, what is the value of x?",
    choices: ["13", "6.5", "−13", "2.6"],
    answer: 0,
    explanation:
      "3(2x − 1) − 4(x + 2) = 15 → 6x − 3 − 4x − 8 = 15 → 2x − 11 = 15 → 2x = 26 → x = 13.",
  },
  {
    id: "alg-49",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 1,
    prompt:
      "What is the y-intercept of the line given by the equation y = −2x + 7?",
    choices: ["7", "−2", "−7", "2"],
    answer: 0,
    explanation: "In the form y = mx + b, the y-intercept is b = 7.",
  },
  {
    id: "alg-50",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 2,
    prompt:
      "A line passes through (−2, 3) and (2, 11). What is the equation of the line?",
    choices: ["y = 2x + 7", "y = 2x + 3", "y = 4x + 7", "y = 2x − 7"],
    answer: 0,
    explanation:
      "Slope = (11 − 3)/(2 − (−2)) = 8/4 = 2. Using point (−2, 3): y − 3 = 2(x + 2) → y = 2x + 7.",
  },
  {
    id: "alg-51",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 3,
    prompt:
      "For what value of c does the system 3x + 4y = 12 and 6x + 8y = c have infinitely many solutions?",
    choices: ["24", "12", "6", "48"],
    answer: 0,
    explanation:
      "Multiplying the first equation by 2 gives 6x + 8y = 24. For the system to have infinitely many solutions, the second equation must be identical, so c = 24.",
  },
  {
    id: "alg-52",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 1,
    prompt:
      "What is the smallest integer value of x that satisfies 2x + 3 ≥ 9?",
    choices: ["3", "4", "2", "6"],
    answer: 0,
    explanation:
      "2x + 3 ≥ 9 → 2x ≥ 6 → x ≥ 3, so the smallest integer value is 3.",
  },
  {
    id: "alg-53",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in two variables",
    difficulty: 2,
    prompt:
      "If x − 2y ≥ 8 and x = 0, what is the maximum possible value of y?",
    choices: ["−4", "4", "−8", "8"],
    answer: 0,
    explanation:
      "Substituting x = 0: −2y ≥ 8 → y ≤ −4 (the inequality flips when dividing by a negative number), so the maximum value of y is −4.",
  },
  {
    id: "alg-54",
    module: "math",
    domain: "Algebra",
    skill: "Word problems",
    difficulty: 3,
    prompt:
      "A jar contains only nickels and dimes worth $3.75 in total. There are 45 coins altogether. How many dimes are in the jar?",
    choices: ["30", "15", "20", "25"],
    answer: 0,
    explanation:
      "Let n + d = 45 and 0.05n + 0.10d = 3.75. Substituting n = 45 − d: 0.05(45 − d) + 0.10d = 3.75 → 2.25 + 0.05d = 3.75 → d = 30.",
  },
  {
    id: "alg-55",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in one variable",
    difficulty: 1,
    prompt: "If 7x − 2 = 5x + 12, what is the value of x?",
    choices: ["7", "14", "5", "−7"],
    answer: 0,
    explanation: "7x − 2 = 5x + 12 → 2x = 14 → x = 7.",
  },
  {
    id: "alg-56",
    module: "math",
    domain: "Algebra",
    skill: "Linear equations in two variables",
    difficulty: 2,
    prompt: "If 3x + 4y = 24 and x = 4, what is the value of y?",
    choices: ["3", "4", "6", "2"],
    answer: 0,
    explanation:
      "Substituting x = 4: 3(4) + 4y = 24 → 12 + 4y = 24 → 4y = 12 → y = 3.",
  },
  {
    id: "alg-57",
    module: "math",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: 3,
    prompt:
      "The function h is linear. If h(2) = 3 and h(−1) = 12, what is the value of h(0)?",
    choices: ["9", "3", "6", "12"],
    answer: 0,
    explanation:
      "Slope = (12 − 3)/(−1 − 2) = 9/(−3) = −3, so h(x) = −3x + b. Using h(2) = 3: 3 = −6 + b → b = 9. Then h(0) = 9.",
  },
  {
    id: "alg-58",
    module: "math",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: 1,
    prompt: "If x = 3y and 2x + y = 21, what is the value of y?",
    choices: ["3", "9", "7", "6"],
    answer: 0,
    explanation:
      "Substitute x = 3y into 2x + y = 21: 2(3y) + y = 21 → 7y = 21 → y = 3.",
  },
  {
    id: "alg-59",
    module: "math",
    domain: "Algebra",
    skill: "Linear inequalities in one variable",
    difficulty: 2,
    prompt:
      "A student needs an average of at least 90 on three tests to earn an A. The student scored 85 and 92 on the first two tests. What is the minimum score needed on the third test to earn an A?",
    choices: ["93", "90", "88", "95"],
    answer: 0,
    explanation:
      "(85 + 92 + x)/3 ≥ 90 → 177 + x ≥ 270 → x ≥ 93, so the minimum score needed is 93.",
  }
);
