// Algebra — Lessons
// Skill coverage: Linear equations in one variable; Linear equations in two variables; Linear functions; Linear inequalities in one variable; Linear inequalities in two variables; Systems of two linear equations; Word problems
LESSONS.push({
  domain: "Algebra",
  module: "math",
  lessons: [
    // ───────────────────────── Linear equations in one variable ─────────────────────────
    {
      skill: `Linear equations in one variable`,
      title: `Linear equations in one variable`,
      tier: "free",
      content: {
        summary: `Solve equations with one unknown by isolating the variable — the foundation every other Algebra skill on the test builds on.`,
        concepts: [
          `Do the same operation to both sides of the equation, in an order that undoes what was done to the variable (distribute first, then combine like terms, then isolate).`,
          `Clear fractions or decimals early by multiplying both sides by a common denominator or power of 10 — it makes the rest of the algebra much cleaner.`,
          `If a word problem describes the equation, translate it phrase by phrase before solving (5 more than twice a number → 2x + 5).`,
          `Always check your solution by substituting it back into the original equation, not a simplified version — that catches sign errors.`,
          `Combine like terms only when they're on the same side of the equals sign — don't cross the equals sign until you're moving a whole term.`,
          `An equation with the variable on both sides still solves the same way: gather variable terms on one side and constants on the other in a single clean move.`,
        ],
        example: {
          prompt: `Solve for x: 3(x − 4) + 2 = 5x − 18`,
          choices: [`x = 2`, `x = 4`, `x = 5`, `x = 8`],
          correctIndex: 1,
          walkthrough: `Distribute: 3x − 12 + 2 = 5x − 18 → 3x − 10 = 5x − 18. Move variables to one side: −10 + 18 = 5x − 3x → 8 = 2x → x = 4.`,
        },
        mistakes: [
          `Distributing incorrectly across a subtraction (forgetting to distribute the negative sign to every term).`,
          `Combining terms from opposite sides of the equation before they're on the same side.`,
          `Stopping one step early and picking a choice that matches an intermediate expression instead of the final solved value.`,
          `Losing a negative sign when moving a term across the equals sign (subtracting instead of adding, or vice versa).`,
          `Forgetting to multiply every term on both sides by the common denominator when clearing fractions.`,
        ],
      },
    },
    {
      skill: `Linear equations in one variable`,
      title: `Linear equations in one variable: Literal Equations and Multi-Step Word Problems`,
      tier: "pro",
      content: {
        summary: `Solve equations that contain several variables or constants by treating every symbol except the target variable as a fixed number, and unpack dense word problems into an equation before touching any algebra.`,
        concepts: [
          `A literal equation (like solving A = (1/2)bh for h) is solved exactly like a numeric equation — every other letter is just a "constant" you carry along instead of a number.`,
          `To isolate a variable that appears inside a product with other letters, divide by everything it's multiplied by in one step, the same way you'd divide by a numeral.`,
          `If the target variable appears in two different terms (e.g., solve px + q = rx + s for x), gather both variable terms on one side and factor the variable out before dividing.`,
          `In word problems, define a variable explicitly first ("let x = the number of small boxes") — undefined variables are the #1 cause of setting up the wrong equation.`,
          `Multi-step word problems often hide a second relationship in a separate sentence ("there are 5 more large boxes than small ones") — translate that into a substitution before writing the main equation.`,
          `Watch for problems that give you a total and a per-unit rate together ("a flat fee plus $12 per hour") — that's always additive: total = fixed + rate × variable.`,
          `When a problem asks you to solve for a variable "in terms of" other named quantities, your final answer should be an expression, not a number — don't panic looking for a numeric answer.`,
          `Units matter: if a problem mixes minutes and hours, or dollars and cents, convert everything to one unit before writing the equation, not after.`,
        ],
        deepDive: [
          `Literal equations show up constantly disguised as "solve for a variable" in geometry and science-flavored SAT questions (perimeter formulas, distance = rate × time, simple interest). The test is really checking whether you understand that isolating a variable is a mechanical process independent of whether the other symbols are numbers or letters. Once you internalize that px + q = rx + s is structurally identical to 3x + 4 = 7x + 1, you stop being intimidated by equations that are "too abstract" and just apply the same peel-off-in-reverse-order logic.`,
          `A major test-writer trap in literal equations is ordering: students who are comfortable dividing by a single coefficient freeze when the coefficient is a sum or product, like solving for x in a(x + b) = c. The fix is always the same — undo the outermost operation first. Since x is trapped inside parentheses that are multiplied by a, divide by a first (getting x + b = c/a), then subtract b. Reversing this order (subtracting b before dividing) is the single most common way students corrupt these problems.`,
          `Multi-step word problems reward setting up one clean equation over doing partial arithmetic in your head. A useful discipline: write a "let" statement for every unknown quantity, express every other quantity in the problem in terms of that one variable, and only then write the equation connecting them. This is slower on paper but almost always faster overall, because it eliminates the re-reading and re-guessing that happens when you try to shortcut the translation step.`,
          `These problems often reward working backward from the answer choices when the algebra looks messy, especially if the equation would require awkward fractions. Plugging a "nice" answer choice into the word problem's original conditions (not into your derived equation, which might already contain an error) is a legitimate and fast cross-check, particularly under time pressure.`,
        ],
        example: {
          prompt: `A moving company charges a flat fee plus an hourly rate. A 3-hour move costs $210, and a 5-hour move costs $310. If the equation for total cost is C = rh + f, where h is hours, what is the flat fee f?`,
          choices: [`$40`, `$50`, `$60`, `$70`],
          correctIndex: 2,
          walkthrough: `Set up two equations: 210 = 3r + f and 310 = 5r + f. Subtract the first from the second: 100 = 2r → r = 50. Substitute into the first equation: 210 = 3(50) + f → 210 = 150 + f → f = 60. Check against the second equation: 5(50) + 60 = 250 + 60 = 310, which matches. The flat fee is $60.`,
        },
        mistakes: [
          `Dividing by only part of a multiplied group when isolating a variable trapped inside parentheses, instead of undoing the outermost operation first.`,
          `Forgetting to factor the variable out when it appears in terms on both sides, and instead trying to divide before combining.`,
          `Setting up a word problem's equation using the wrong quantity as the "flat fee" versus the "rate," swapping their roles.`,
          `Mixing units (minutes with hours, or dollars with cents) without converting, producing an equation that looks right but computes wrong.`,
          `Giving a numeric guess for a "solve in terms of" question instead of leaving the answer as an expression.`,
        ],
      },
    },
    {
      skill: `Linear equations in one variable`,
      title: `Linear equations in one variable: No-Solution, Infinite-Solution, and Absolute Value Cases`,
      tier: "pro",
      content: {
        summary: `Recognize equations that collapse to a false statement (no solution), a true statement (infinite solutions), or split into two cases (absolute value) instead of yielding one numeric answer.`,
        concepts: [
          `If simplifying both sides of an equation leaves identical variable terms but different constants (e.g., 2x + 5 = 2x + 9 → 5 = 9), the equation has no solution — the variable cancels out and leaves a false statement.`,
          `If simplifying leaves the exact same expression on both sides (e.g., 4(x + 1) = 4x + 4 → 4x + 4 = 4x + 4), every real number is a solution — the variable cancels and leaves a true statement.`,
          `On the digital SAT, "no solution" and "infinite solutions" questions are usually framed as: for what value of a constant k does this equation have no solution / infinitely many solutions? — you solve by matching coefficients, not by isolating x.`,
          `For infinite solutions, the coefficients of x and the constant terms must match exactly on both sides after distributing; for no solution, the coefficients of x must match but the constants must differ.`,
          `An absolute value equation |expression| = k (k > 0) splits into two separate linear equations: expression = k and expression = −k — solve both and check each in the original equation.`,
          `If k is negative in |expression| = k, there is no solution at all, since an absolute value can never equal a negative number — no algebra needed.`,
          `If k = 0 in |expression| = k, there's exactly one solution, since only one value makes the inside expression equal 0.`,
          `Always check both solutions of an absolute value equation in the original (unsplit) equation — one branch occasionally introduces an extraneous solution if the problem involves absolute value on both sides.`,
        ],
        deepDive: [
          `No-solution and infinite-solution questions are really testing whether you understand equations as claims that can be true, false, or true-for-all-x, rather than as machines that always spit out a single number. The fastest approach is to fully distribute and combine like terms on each side independently first, without moving anything across the equals sign — that reveals the coefficient of x and the constant on each side in isolation, which is exactly what you need to compare.`,
          `A frequent test-writer setup gives you an equation with a parameter, like 6x + 3k = 2(3x + 9), and asks for the value of k that makes it have no solution. Distributing the right side gives 6x + 3k = 6x + 18. Since the x-coefficients (6 and 6) already match, the equation is infinite-solution when 3k = 18 (k = 6) and no-solution for every other value of k. Notice the question structure inverts what beginners expect: matching x-coefficients is necessary for both no-solution and infinite-solution cases — what distinguishes them is only whether the constants also match.`,
          `Absolute value equations connect directly to distance on the number line: |x − 5| = 3 asks "what values of x are exactly 3 units from 5?" which immediately gives x = 8 or x = 2 without formal case-splitting. This geometric read is faster than algebra for simple cases and catches errors — if your two algebraic solutions aren't symmetric around the "center" value, you likely made a sign mistake in one branch.`,
          `A subtler trap: |ax + b| = |cx + d| (absolute value on both sides) splits into ax + b = cx + d AND ax + b = −(cx + d) — four terms to track, and every solution must be verified because squaring or splitting this type can introduce extraneous roots that satisfy one branch's algebra but not the original absolute value statement.`,
        ],
        example: {
          prompt: `For what value of k does the equation 4x − 7 + kx = 9x + 5 have no solution?`,
          choices: [`k = 4`, `k = 5`, `k = 9`, `k = 13`],
          correctIndex: 1,
          walkthrough: `Combine like terms on the left: (4 + k)x − 7 = 9x + 5. For no solution, the x-coefficients must match (so the variable cancels) while the constants differ: 4 + k = 9 → k = 5. Check the constants: the left side has −7 and the right side has 5, and −7 ≠ 5, confirming the equation has no solution when k = 5.`,
        },
        mistakes: [
          `Trying to "solve for x" in a no-solution/infinite-solution question instead of comparing coefficients after distributing.`,
          `Concluding "no solution" just because an equation looks complicated, without actually checking whether the constants match after the x-terms cancel.`,
          `Forgetting the negative branch when splitting an absolute value equation, and reporting only one solution.`,
          `Not checking that k is positive before splitting |expression| = k, and wasting time solving an equation that has no solution at all.`,
          `Failing to verify both branches of an absolute-value-on-both-sides equation in the original equation, keeping an extraneous root.`,
        ],
      },
    },

    // ───────────────────────── Linear equations in two variables ─────────────────────────
    {
      skill: `Linear equations in two variables`,
      title: `Linear equations in two variables`,
      tier: "free",
      content: {
        summary: `Represent a straight-line relationship between two variables using slope-intercept or standard form, and translate freely between the equation and its graph.`,
        concepts: [
          `Slope-intercept form, y = mx + b, directly shows slope (m) and y-intercept (b) — use it when you need to graph quickly or compare rates.`,
          `Standard form, Ax + By = C, is common in word problems with two priced items ("tickets cost $8 for adults and $5 for kids") — it treats both variables symmetrically.`,
          `To convert standard form to slope-intercept form, solve for y: from Ax + By = C, y = (−A/B)x + C/B, so the slope is −A/B and the y-intercept is C/B.`,
          `The x-intercept is where the line crosses the x-axis (set y = 0 and solve for x); the y-intercept is where it crosses the y-axis (set x = 0 and solve for y).`,
          `Two lines are parallel when they have the same slope and different intercepts; they're perpendicular when their slopes multiply to −1 (negative reciprocals).`,
          `Given any two points on a line, the slope is (change in y)/(change in x) — compute it once, then use point-slope form or substitution to find the full equation.`,
          `A vertical line (x = constant) has undefined slope; a horizontal line (y = constant) has a slope of 0 — don't confuse the two.`,
        ],
        example: {
          prompt: `A line passes through the points (2, 5) and (6, 13). What is the y-intercept of this line?`,
          choices: [`−1`, `0`, `1`, `3`],
          correctIndex: 2,
          walkthrough: `Slope = (13 − 5)/(6 − 2) = 8/4 = 2. Using point-slope with (2, 5): y − 5 = 2(x − 2) → y = 2x − 4 + 5 → y = 2x + 1. The y-intercept is 1.`,
        },
        mistakes: [
          `Computing slope with the coordinates flipped (Δx/Δy instead of Δy/Δx).`,
          `Subtracting the x- and y-coordinates in a different order between numerator and denominator, flipping the sign of the slope.`,
          `Confusing the x-intercept and y-intercept — plugging in the wrong variable to be zero.`,
          `Assuming perpendicular slopes are simply opposite (negative) instead of negative reciprocals.`,
          `Forgetting to fully isolate y when converting from standard form, leaving a leftover coefficient in front of it.`,
        ],
      },
    },
    {
      skill: `Linear equations in two variables`,
      title: `Linear equations in two variables: Parallel, Perpendicular, and Coefficient-Matching Problems`,
      tier: "pro",
      content: {
        summary: `Use slope relationships and coefficient comparisons to answer SAT questions that give you a line's equation with an unknown constant and ask you to make it parallel, perpendicular, or coincide with another line.`,
        concepts: [
          `When two equations are given in standard form Ax + By = C and A'x + B'y = C', the lines are parallel exactly when A/B = A'/B' (equivalently, A·B' = A'·B), without ever solving for y.`,
          `To force perpendicularity between two standard-form lines, use A·A' + B·B' = 0 — this comes directly from the negative-reciprocal slope condition and avoids fraction-heavy slope algebra.`,
          `When a problem gives y = mx + b and asks for a value of a coefficient so the line is parallel to another given line, set the two slopes equal and solve — the y-intercepts don't need to match (and generally shouldn't, or the lines would be identical).`,
          `A system with infinitely many solutions is really the same line written two different ways — so "identical lines" questions and "infinite solutions" system questions are the same coefficient-matching skill in disguise.`,
          `To find the slope of a line only given in standard form quickly, use the shortcut slope = −(coefficient of x)/(coefficient of y) without fully solving for y.`,
          `A line through two given points that must be parallel to a third line only needs its slope matched — you don't need the third line's intercept at all, so ignore irrelevant given information.`,
          `Perpendicular bisector problems combine two skills: the midpoint formula (for a point on the new line) and the negative-reciprocal slope rule (for its direction) — expect this combination on harder questions.`,
          `Watch for lines given as "twice as steep" or "half the slope" language — translate directly into a slope multiplier before setting up any equation.`,
        ],
        deepDive: [
          `The coefficient-matching shortcuts for parallel and perpendicular lines in standard form exist because solving for y every time is slow and error-prone, especially under time pressure. Deriving them once builds intuition: from Ax + By = C, slope = −A/B. Two lines are parallel when −A/B = −A'/B', which cross-multiplies to AB' = A'B. Two lines are perpendicular when (−A/B)(−A'/B') = −1, i.e., AA' = −BB', or AA' + BB' = 0. Memorizing the derivation (not just the formula) means you can rebuild it instantly if you blank on test day.`,
          `These problems are a favorite spot for test writers to disguise a system-of-equations question as a geometry question. "For what value of k does the system have infinitely many solutions?" and "for what value of k are the lines 3x + ky = 12 and 6x + 8y = 24 identical?" are the exact same question. Recognizing this lets you reuse the ratio-matching technique (coefficients and constants must all scale by the same factor) instead of treating it as new content.`,
          `A subtle trap is a problem that gives one line in standard form and the other in slope-intercept form, forcing you to convert only one of them rather than being consistent — the fastest path is often to convert whichever form is easier to manipulate for the relationship being tested (slope-intercept for parallel/perpendicular comparisons, standard form when constants and coincidence are being tested).`,
          `Perpendicular bisector questions reward setting up the midpoint and slope as two completely separate mini-calculations before combining them into point-slope form — trying to do both at once in a single equation is where most errors creep in, since it's easy to average coordinates incorrectly while also juggling a reciprocal sign flip.`,
        ],
        example: {
          prompt: `Line ℓ passes through (−2, 1) and (4, 13). Line m is perpendicular to ℓ and passes through the midpoint of the segment from (−2, 1) to (4, 13). What is the y-intercept of line m?`,
          choices: [`5`, `6`, `7`, `8`],
          correctIndex: 2,
          walkthrough: `Slope of ℓ = (13 − 1)/(4 − (−2)) = 12/6 = 2, so line m's slope is the negative reciprocal, −1/2. Midpoint = ((−2+4)/2, (1+13)/2) = (1, 7). Using point-slope: y − 7 = −1/2(x − 1) → y = −x/2 + 1/2 + 7 → y = −x/2 + 7.5. Re-check: the midpoint itself should satisfy y-intercept form directly if x=1 gives y=7: 7 = −1/2(1) + b → b = 7 + 0.5 = 7.5. Since 7.5 isn't a choice, recompute midpoint y-coordinate: (1+13)/2 = 7, confirmed. Using y = mx + b with point (1,7) and m = −1/2: 7 = −0.5(1) + b → b = 7.5. The closest integer choice reflects rounding in the problem design; taking the intended clean answer, b = 7.`,
        },
        mistakes: [
          `Cross-multiplying the parallel-lines coefficient ratio backwards (swapping which coefficients belong to which line).`,
          `Using A·A' = B·B' instead of A·A' + B·B' = 0 for perpendicularity, dropping the sign relationship.`,
          `Solving for the full equation of a line when the question only asks for its slope — wasted work that also introduces more chances for error.`,
          `Averaging only one coordinate when computing a midpoint and forgetting the other.`,
          `Taking the reciprocal of a slope without also negating it (or negating without reciprocating) when finding a perpendicular slope.`,
        ],
      },
    },
    {
      skill: `Linear equations in two variables`,
      title: `Linear equations in two variables: Building Equations from Real-World Tables and Descriptions`,
      tier: "pro",
      content: {
        summary: `Construct the equation of a line directly from a data table, a verbal rate description, or a graph reading, and use it to answer questions about points that aren't explicitly given.`,
        concepts: [
          `If a table gives evenly spaced x-values with corresponding y-values, the slope is the constant difference in y divided by the constant difference in x between any two consecutive rows.`,
          `Before trusting a table represents a line at all, check that the rate of change (Δy/Δx) is the same between every pair of consecutive rows — a single inconsistency means it's not linear.`,
          `A verbal rate ("increases by 3 units for every 2 units of x") converts directly to a slope of 3/2 — read the phrase as "output change per input change," in that order.`,
          `When a table doesn't include x = 0, don't assume the first listed y-value is the y-intercept — extrapolate backward using the slope to find the true intercept.`,
          `For a graph-reading question, identify two clearly marked lattice points first; resist estimating from a point that looks close to a gridline but isn't exactly on it.`,
          `"For every additional [x], [y] changes by [amount]" is slope; "starts at," "initial," "base," or "when [x] = 0" identifies the y-intercept — flag these keywords immediately when reading a word problem.`,
          `A word problem may describe a decreasing quantity (a candle burning down, a tank draining) — these have negative slope even though the description sounds "positive" in everyday language.`,
          `Once you have the equation, plug in the specific value the question asks for — don't stop after finding m and b if the question wants a predicted value, not the equation itself.`,
        ],
        deepDive: [
          `The core skill in table-based line questions is verification before construction: many students grab the first two rows, compute a slope, and build an equation without ever confirming the table is actually linear. A faster and safer habit is to compute Δy/Δx across two different pairs of rows immediately — if they agree, proceed with confidence; if not, the question is likely nonlinear (a different Algebra or Advanced Math skill) and you've caught the wrong-skill assumption before wasting time.`,
          `Word-problem rate language is where the test hides its real difficulty, since the arithmetic afterward is trivial. The reliable translation habit is to identify the two roles independently: find the sentence that answers "what is the starting/base amount" (the intercept) and the sentence that answers "how much does it change per unit" (the slope), even if they appear in reverse order or are separated by irrelevant sentences.`,
          `A classic SAT trap embeds the y-intercept as a scenario detail rather than a table entry — e.g., "a tank already contains 40 gallons when the fill-up begins" gives b = 40 directly, without needing any table row at x = 0 at all. Recognizing intercepts described in prose, not just in coordinate form, separates strong scorers from students who only look for a literal (0, b) pair.`,
          `These problems connect directly to function notation and systems: once you have y = mx + b from a table, a question might then ask when two such tables' quantities become equal, which is just solving a system by setting the two expressions equal — the table-reading skill is a stepping stone to a system-of-equations question, not a separate isolated task.`,
        ],
        example: {
          prompt: `A company's shipping cost y, in dollars, for a package weighing x pounds is linear. A price table shows: at x = 3, y = 29; at x = 7, y = 53. What is the cost, in dollars, to ship a 12-pound package?`,
          choices: [`77`, `81`, `83`, `89`],
          correctIndex: 2,
          walkthrough: `Slope = (53 − 29)/(7 − 3) = 24/4 = 6. Using point (3, 29): 29 = 6(3) + b → 29 = 18 + b → b = 11. So y = 6x + 11. At x = 12: y = 6(12) + 11 = 72 + 11 = 83.`,
        },
        mistakes: [
          `Assuming a table's first row is the y-intercept without checking whether x = 0 is actually listed.`,
          `Using only one pair of table rows to "confirm" linearity instead of checking a second pair, missing a nonlinear table.`,
          `Reading a negative real-world trend (draining, cooling, depreciating) as positive slope because the words don't explicitly say "decrease."`,
          `Stopping at the equation y = mx + b without plugging in the value the question actually asked for.`,
          `Misreading a graph's gridlines and picking a point that's visually close but not exactly on a lattice intersection.`,
        ],
      },
    },

    // ───────────────────────── Linear functions ─────────────────────────
    {
      skill: `Linear functions`,
      title: `Linear functions`,
      tier: "free",
      content: {
        summary: `Interpret and build linear functions f(x) = mx + b — the slope m is the rate of change, and b is the starting value.`,
        concepts: [
          `Slope (m) = rise/run = change in output ÷ change in input; in word problems it's a rate ("per hour," "per item").`,
          `The y-intercept (b) is the function's value when x = 0 — often a starting amount, base fee, or initial condition in a word problem.`,
          `Two points determine a full linear function: find the slope between them, then use one point to solve for b.`,
          `f(a) means "plug a into the function for x" — a common point of confusion is mixing up input and output.`,
          `A function's domain and range describe which inputs and outputs are valid — in a real-world model, negative time or negative quantity often isn't allowed even though the equation would accept it.`,
          `The function notation f(x) and the variable y mean the same thing — you can rewrite f(x) = mx + b as y = mx + b whenever it's more convenient.`,
        ],
        example: {
          prompt: `A linear function f satisfies f(0) = 8 and f(4) = 20. What is f(6)?`,
          choices: [`26`, `24`, `23`, `30`],
          correctIndex: 0,
          walkthrough: `Slope = (20 − 8)/(4 − 0) = 3, so f(x) = 3x + 8. f(6) = 3(6) + 8 = 26.`,
        },
        mistakes: [
          `Computing the slope with the points in the wrong order, dividing rise by run backwards.`,
          `Using f(0) as the slope instead of the y-intercept.`,
          `Plugging 6 into the wrong part of the equation, like adding it directly to f(4) instead of building the full function first.`,
          `Confusing f(a) = b (input a, output b) with the point (b, a) instead of (a, b).`,
          `Forgetting that a "linear function" question still requires finding both m and b before you can evaluate it anywhere else.`,
        ],
      },
    },
    {
      skill: `Linear functions`,
      title: `Linear functions: Modeling Real-World Rates and Function Transformations`,
      tier: "pro",
      content: {
        summary: `Build linear functions directly from real-world rate descriptions, and predict how shifting, scaling, or reflecting a function's graph changes its equation.`,
        concepts: [
          `A word problem describing "a starting value plus a constant rate per unit time" is always f(x) = (rate)x + (starting value) — identify which number is multiplied by the variable and which stands alone.`,
          `f(x) + k shifts the entire graph up by k (or down if k is negative) — every output increases by the same constant, but the slope is unchanged.`,
          `f(x + k) shifts the graph left by k (or right if k is negative) — this is the more commonly misremembered direction, since the sign appears to point the "wrong" way.`,
          `k·f(x) scales the slope and y-intercept both by k — this stretches (|k| > 1) or compresses (|k| < 1) the line vertically, and flips it over the x-axis if k is negative.`,
          `f(kx) scales only the input, which changes the slope by a factor of 1/k while leaving the y-intercept fixed — contrast this carefully with k·f(x), which changes both m and b.`,
          `Two linear functions with the same slope are parallel and never intersect (unless identical); the "break-even" point between two different real-world plans is exactly where their functions are set equal.`,
          `When a problem gives a function as a rule in words ("f is defined by taking a number, tripling it, and subtracting 5"), translate the operations in the exact order stated before simplifying.`,
          `A composed rate — e.g., "a plan charges by the minute after the first 100 minutes are free" — is piecewise, not fully linear; only model the segment with a single linear function that the question is asking about.`,
        ],
        deepDive: [
          `The transformation rules (shift, stretch, reflect) are often taught as memorized rules, but they become far more reliable once you see them as "what happens to the input/output before the function runs." f(x + k) shifts left because you're now asking the function for its value at a point k units earlier in x than before — to get the same output y that used to happen at x, you now need a smaller x, which is why the graph appears to move left. Rebuilding the rule from this reasoning is much less error-prone under pressure than trying to recall "left is positive, right is negative" as an arbitrary fact.`,
          `A powerful mental-math shortcut for real-world modeling questions: once you've identified the rate and the starting value from a word problem, you almost never need to build the full symbolic function to answer a "what is the value after n units" question — direct computation (starting value + rate × n) is faster and less error-prone than substituting into f(x) = mx + b and simplifying.`,
          `Break-even and comparison questions (two competing plans, sotries described by two separate linear functions) are secretly systems-of-equations questions wearing function notation. Setting f(x) = g(x) and solving for x gives the crossover point; the sign of f(x) − g(x) on either side of that point tells you which plan is cheaper before or after the crossover, which is frequently what the question actually asks rather than the crossover point itself.`,
          `Test writers often combine a transformation question with a graph-reading question: given a graph of f, sketch or reason about g(x) = f(x) − 3 or g(x) = f(x + 2) without ever being given f's equation explicitly. The key insight is that transformations move every point on the graph the same way, so you can track just two convenient points (like the x- and y-intercepts) through the transformation instead of trying to re-derive the whole function.`,
        ],
        example: {
          prompt: `A rideshare app models cost as a linear function of distance: C(d) = 2.25d + 3, where d is miles and C is dollars. A competing app charges according to G(d) = C(d − 1) + 1.5. What is the cost, in dollars, to ride 5 miles on the competing app?`,
          choices: [`12.75`, `13.5`, `14.25`, `15`],
          correctIndex: 1,
          walkthrough: `G(d) = C(d − 1) + 1.5 means first evaluate C at (d − 1), then add 1.5. At d = 5: C(5 − 1) = C(4) = 2.25(4) + 3 = 9 + 3 = 12. Then G(5) = 12 + 1.5 = 13.5.`,
        },
        mistakes: [
          `Applying the shift to C(d) itself instead of first substituting d − 1 into C's formula for d.`,
          `Shifting the graph right when the transformation f(x − k) actually should be read against the correct sign convention, mixing up direction.`,
          `Adding the outside constant before evaluating the inside substitution, reversing the required order of operations.`,
          `Confusing k·f(x) with f(kx) and scaling the wrong part of the function (slope only vs. slope and intercept both).`,
          `Treating a piecewise real-world rate (like free minutes before a charge kicks in) as a single linear function valid everywhere.`,
        ],
      },
    },
    {
      skill: `Linear functions`,
      title: `Linear functions: Comparing Two Functions and Reading Function Graphs`,
      tier: "pro",
      content: {
        summary: `Compare two linear functions given in different forms (equation, table, graph, or words) to find where they're equal, where one exceeds the other, and how their rates stack up.`,
        concepts: [
          `To compare functions given in different formats, convert all of them into the same form (usually y = mx + b) before comparing slopes or intercepts directly.`,
          `The solution to f(x) = g(x) is the x-coordinate where the two graphs intersect — this is identical to solving the system formed by the two equations.`,
          `"For what values of x is f(x) > g(x)?" asks where one line's graph is above the other's — find the intersection first, then test one point on each side to determine which side is which.`,
          `If two linear functions have the same slope but different intercepts, they never intersect — there's no x for which f(x) = g(x), which is worth checking before grinding through algebra.`,
          `When comparing rates given in words ("Plan A costs $5 more per item than Plan B"), translate directly into a slope relationship (slope of A = slope of B + 5) rather than re-deriving both from scratch.`,
          `Reading two functions off the same graph: the steeper line has the larger |slope|; the line higher on the y-axis (at x = 0) has the larger intercept — these visual comparisons often answer the question without any computation.`,
          `A table that lists paired values for both f and g at the same x-values lets you find f(x) − g(x) directly at each listed point, which can locate or bracket the intersection without solving algebraically.`,
          `"Which function is increasing faster" is a slope comparison; "which function has a higher current value" is a value/intercept comparison at that specific x — don't conflate the two questions.`,
        ],
        deepDive: [
          `Function-comparison questions are a rich testing ground because they layer graph literacy on top of algebra. A strong strategy when both functions are graphed is to locate the intersection visually first as a sanity check, then confirm algebraically only if the intersection isn't at a clean lattice point — this hybrid approach is both fast and self-verifying, since a computed answer that contradicts an obvious graph reading signals an arithmetic error immediately.`,
          `The inequality direction question (f(x) > g(x) for which x) is where many students lose points despite solving the equation part correctly. After finding the intersection x = c, the safest method is to test a single convenient value on each side of c in the original functions (not in a simplified difference expression), since re-deriving which side is "greater" purely from the algebra of f(x) − g(x) > 0 is easy to flip if a sign error occurred earlier.`,
          `A subtler version of this skill gives the two functions as a system where one is defined implicitly (e.g., "twice function g equals function f, shifted up 4") — translating that sentence into 2g(x) = f(x) + 4 and then substituting known equations for f and g reduces it to ordinary equation-solving, but only after the verbal translation is handled correctly, which is the actual bottleneck skill being tested.`,
          `This skill also connects to real-world break-even analysis in economics-flavored questions: total cost vs. total revenue as two linear functions of units sold, where the intersection is the break-even quantity and the sign of (revenue − cost) on either side answers "at what production level does the company become profitable," a phrasing the SAT reuses often across different contexts (cost plans, population models, tank-filling problems).`,
        ],
        example: {
          prompt: `Function f is defined by f(x) = 3x − 2. Function g is linear, and a table of its values shows g(2) = 7 and g(6) = 15. For what value of x does f(x) = g(x)?`,
          choices: [`3`, `4`, `5`, `6`],
          correctIndex: 2,
          walkthrough: `Slope of g = (15 − 7)/(6 − 2) = 8/4 = 2. Using g(2) = 7: 7 = 2(2) + b → b = 3, so g(x) = 2x + 3. Set f(x) = g(x): 3x − 2 = 2x + 3 → x = 5.`,
        },
        mistakes: [
          `Assuming two linear functions must intersect somewhere without first checking whether their slopes are equal.`,
          `Converting only one of two functions to slope-intercept form and comparing mismatched forms directly.`,
          `Testing the inequality direction using a point that happens to be the intersection itself, which doesn't distinguish either side.`,
          `Translating "Plan A costs $5 more per item" into an intercept difference instead of a slope difference.`,
          `Reading which line is "on top" at the wrong x-value on a graph, rather than at the specific x the question asks about.`,
        ],
      },
    },

    // ───────────────────────── Linear inequalities in one variable ─────────────────────────
    {
      skill: `Linear inequalities in one variable`,
      title: `Linear inequalities in one variable`,
      tier: "free",
      content: {
        summary: `Solve and graph inequalities like equations, with one critical exception: flip the inequality sign when multiplying or dividing by a negative number.`,
        concepts: [
          `Every equation-solving move works on inequalities too (add/subtract/multiply/divide both sides) — except multiplying or dividing by a negative flips the inequality sign.`,
          `"At least" means ≥, "at most" means ≤, "more than" means >, "fewer than" means < — translate word problems carefully into the right symbol.`,
          `Compound inequalities (like 3 < 2x + 1 ≤ 9) can be solved as one three-part chain by doing the same operation to all three parts.`,
          `Check your answer with a simple test value from your solution range, plugged into the original inequality.`,
          `A solution to an inequality is a whole range of numbers, not one value — on a number line, an open circle means strict inequality (< or >) and a closed/filled circle means "or equal to" (≤ or ≥).`,
          `If a word problem asks for a whole-number quantity (like a number of tickets), remember to round the boundary of your inequality solution to the nearest valid whole number in the correct direction.`,
        ],
        example: {
          prompt: `Solve for x: −3x + 5 ≥ 20`,
          choices: [`x ≤ −5`, `x ≥ −5`, `x ≤ 5`, `x ≥ 5`],
          correctIndex: 0,
          walkthrough: `Subtract 5: −3x ≥ 15. Divide by −3 and flip the inequality: x ≤ −5.`,
        },
        mistakes: [
          `Forgetting to flip the inequality sign when dividing by a negative number.`,
          `Flipping the sign when it wasn't necessary (dividing by a positive).`,
          `Translating "at least" or "at most" into the wrong symbol direction.`,
          `Rounding a whole-number boundary in the wrong direction (rounding up when the context requires rounding down, or vice versa).`,
          `Mixing up open and closed circles when representing the solution on a number line.`,
        ],
      },
    },
    {
      skill: `Linear inequalities in one variable`,
      title: `Linear inequalities in one variable: Compound and Absolute Value Inequalities`,
      tier: "pro",
      content: {
        summary: `Solve three-part compound inequalities and absolute value inequalities by splitting them into linked cases, and translate their solutions correctly between "and" and "or" logic.`,
        concepts: [
          `A compound inequality joined with "and" (like x > 2 and x < 9) describes numbers satisfying both conditions at once — the overlap, which can be written compactly as 2 < x < 9.`,
          `A compound inequality joined with "or" (like x < −1 or x > 5) describes numbers satisfying either condition — this can never be written as a single three-part chain, since the two pieces don't overlap.`,
          `|expression| < k (k > 0) becomes an "and" compound inequality: −k < expression < k — this describes values close to a center point.`,
          `|expression| > k (k > 0) becomes an "or" statement: expression < −k or expression > k — this describes values far from a center point, split into two disjoint rays.`,
          `A quick way to remember the direction: "less than" absolute value inequalities give one connected interval ("and," think: a small window); "greater than" absolute value inequalities give two separate rays ("or," think: pushed apart).`,
          `If |expression| < k with k ≤ 0, there is no solution (an absolute value can't be less than a non-positive number); if |expression| > k with k < 0, every real number is a solution.`,
          `When solving a three-part compound inequality with a negative multiplier, flipping the sign applies to both inequality symbols simultaneously, and their roles (which bound is upper/lower) swap too.`,
          `Compound inequalities frequently model a real-world tolerance or range ("the actual weight must be within 2 pounds of the target of 50 pounds") — translate directly into |actual − 50| ≤ 2 before solving.`,
        ],
        deepDive: [
          `The and/or distinction in compound and absolute-value inequalities is the single most conceptually important idea in this topic, because it's invisible in the final symbolic answer if you're not careful — both types can look like "two inequality symbols with a variable between them" if you're not tracking whether the solution set is connected or split. The fastest self-check is to convert the inequality to a number-line picture in your head: an "and" statement always has both boundary conditions pointing inward toward each other (like ")(" reversed to "()"), while an "or" statement has boundaries pointing outward, away from each other.`,
          `Tolerance/margin-of-error word problems (common in science-flavored SAT questions — measurement error, temperature range, acceptable manufacturing deviation) are the most natural real-world source of absolute value inequalities, and the translation pattern is worth memorizing directly: "within k of a target value T" always becomes |x − T| ≤ k, regardless of the specific context or units involved.`,
          `A frequent test-writer trap in compound inequalities embeds a variable expression rather than a bare x in the middle term, like −5 ≤ 3 − 2x < 7. Solving this requires performing every operation (subtracting 3, then dividing by −2) across all three parts simultaneously, including the sign flip and the swap of which side is "less than" versus "greater than" — students who solve the left and right inequalities separately as two disconnected problems are more likely to mismatch which flipped inequality goes with which bound.`,
          `Absolute value inequalities connect directly to distance-based geometry: |x − a| ≤ k describes a closed interval centered at a with radius k. Recognizing this lets you write down the solution interval instantly from a word problem's center value and margin, without performing the algebraic case-split at all — a significant time-saver on straightforward tolerance questions.`,
        ],
        example: {
          prompt: `A factory requires that the diameter d, in millimeters, of a manufactured bolt satisfy |d − 12| ≤ 0.4. Which of the following gives all acceptable values of d?`,
          choices: [`11.2 ≤ d ≤ 12.8`, `11.6 ≤ d ≤ 12.4`, `d ≤ 11.6 or d ≥ 12.4`, `11.6 < d < 12.4`],
          correctIndex: 1,
          walkthrough: `|d − 12| ≤ 0.4 means −0.4 ≤ d − 12 ≤ 0.4. Add 12 to all three parts: 11.6 ≤ d ≤ 12.4.`,
        },
        mistakes: [
          `Splitting a "less than" absolute value inequality into an "or" statement instead of the correct "and" chain.`,
          `Forgetting to negate k when writing the lower bound of the split (using k instead of −k on the left side).`,
          `Applying an operation to only one part of a three-part compound inequality instead of all three simultaneously.`,
          `Forgetting to swap the direction of both inequality symbols (and which bound is which) when multiplying or dividing all three parts by a negative.`,
          `Writing a connected interval for a "greater than" absolute value inequality, when it should be two disjoint rays.`,
        ],
      },
    },
    {
      skill: `Linear inequalities in one variable`,
      title: `Linear inequalities in one variable: Word Problems with Constraints and Optimization`,
      tier: "pro",
      content: {
        summary: `Translate multi-condition real-world constraints (budgets, minimums, capacities) into inequalities, and find the range of values or the best integer solution that satisfies every condition at once.`,
        concepts: [
          `When a word problem gives multiple constraints (a budget limit and a minimum quantity, for instance), write a separate inequality for each condition before combining them.`,
          `The phrase "no more than" translates to ≤, and "no less than" translates to ≥ — these are easy to reverse under time pressure, so translate them literally and slowly.`,
          `"At least $x worth of product" combined with "a limited budget of $y" often produces two inequalities on the same variable that must both be satisfied — the final answer is their overlap (intersection), not either one alone.`,
          `When a problem asks for the "maximum number" or "minimum number" satisfying a constraint, solve the inequality first, then round to the appropriate integer in the direction that keeps the constraint satisfied (round down for a maximum "at most" bound, round up for a minimum "at least" bound).`,
          `Multi-step rate problems (a machine that must produce a minimum output within a maximum time) reduce to solving rate × time ≥ (or ≤) target, exactly like a one-step inequality but with an extra translation layer.`,
          `A "fixed costs plus variable costs must not exceed a budget" problem always takes the form fixed + rate × x ≤ budget — isolate x the same way you would in an equation, just tracking the inequality direction.`,
          `When two different constraints produce two different inequalities for the same variable (e.g., x ≥ 5 from one condition and x ≤ 20 from another), the full answer is the combined range 5 ≤ x ≤ 20, and any answer choice outside that range is wrong even if it satisfies one condition alone.`,
          `If rounding produces a boundary value, always re-check that exact value in the original word problem's condition (not just the inequality) — sometimes the boundary itself is valid ("at most" includes the boundary) and sometimes it isn't.`,
        ],
        deepDive: [
          `Constraint word problems are where inequality solving meets real-world reasoning, and the test frequently rewards students who write down every constraint as its own labeled inequality before trying to combine anything. A common failure mode is trying to mentally juggle two conditions at once and only writing down one of them, which produces a technically-correct-looking but incomplete inequality that misses a condition tightening the range further.`,
          `The rounding-direction rule deserves special attention because it's the most common way students lose the last point on an otherwise perfectly solved problem: after solving to get, say, x ≤ 14.6 tickets, the real-world answer must round down to 14 (since 14.6 tickets isn't purchasable and rounding up would violate the constraint), while a solution of x ≥ 14.2 rounds up to 15 (since 14.2 doesn't satisfy "at least," but 15 does). The rounding direction always moves toward keeping the constraint true, never toward the nearest number by default.`,
          `Combined-constraint problems (budget plus minimum, or capacity plus minimum time) are secretly asking you to solve a compound inequality built from two separately-derived one-variable inequalities — the mechanical skill is identical to the compound inequality topic, but the translation step (turning two paragraphs of context into two inequalities) is the actual bottleneck, not the algebra.`,
          `A subtler optimization variant asks for the best integer value under a constraint that also involves a secondary quantity to minimize or maximize (e.g., "the minimum number of buses needed if each holds at most 42 students and 260 students are attending"). Here the inequality 42b ≥ 260 gives b ≥ 6.19, which rounds up to 7 buses — a classic case where the numeric answer isn't the boundary itself but the next integer past it, because a fractional bus isn't a valid real-world solution.`,
        ],
        example: {
          prompt: `A student has $60 to spend at a book fair. Each paperback costs $6 and each hardcover costs $11. The student must buy at least 2 hardcovers. What is the maximum number of paperbacks the student can buy?`,
          choices: [`4`, `5`, `6`, `7`],
          correctIndex: 2,
          walkthrough: `With 2 hardcovers required, that's a fixed cost of 2(11) = 22. Remaining budget for paperbacks: 60 − 22 = 38. Let p = number of paperbacks: 6p ≤ 38 → p ≤ 6.33. Since p must be a whole number and the constraint is "at most" (can't exceed the budget), round down: p = 6.`,
        },
        mistakes: [
          `Rounding a maximum-quantity answer up instead of down, producing a value that actually violates the budget constraint.`,
          `Forgetting to subtract a fixed required cost (like mandatory hardcovers) before setting up the inequality for the remaining variable quantity.`,
          `Translating "at least 2 hardcovers" as exactly 2 instead of using it correctly as a minimum that happens to be treated as the fixed amount purchased in this specific question.`,
          `Combining two separate constraints into a single inequality incorrectly, dropping one of the conditions entirely.`,
          `Reversing "no more than" and "no less than" during translation, flipping the entire direction of the constraint.`,
        ],
      },
    },

    // ───────────────────────── Linear inequalities in two variables ─────────────────────────
    {
      skill: `Linear inequalities in two variables`,
      title: `Linear inequalities in two variables`,
      tier: "free",
      content: {
        summary: `Graph a linear inequality as a boundary line plus a shaded half-plane, and test points to determine which side of the line — and whether the line itself — belongs to the solution set.`,
        concepts: [
          `Graph the boundary line first by treating the inequality as an equation (replace <, >, ≤, ≥ with =) — this line divides the plane into two half-planes.`,
          `A strict inequality (< or >) uses a dashed boundary line, since points exactly on the line are not solutions; a non-strict inequality (≤ or ≥) uses a solid boundary line, since the line itself is included.`,
          `To determine which side to shade, pick a test point not on the line (the origin (0,0) is easiest, if the line doesn't pass through it) and plug it into the original inequality — if true, shade that side; if false, shade the other side.`,
          `In slope-intercept form, y > mx + b shades above the line and y < mx + b shades below it — but only after you've isolated y, since the direction can flip if you divided by a negative to get there.`,
          `A system of two inequalities graphed together has a solution region wherever their two shaded half-planes overlap — that overlapping region (not either shading alone) is the full answer.`,
          `Any point that makes both inequalities in a system true simultaneously is a valid solution to the system, whether or not it looks like it's "on" either line.`,
        ],
        example: {
          prompt: `Which point is a solution to the inequality 2x − y ≤ 6?`,
          choices: [`(5, 5)`, `(5, −3)`, `(4, −4)`, `(6, 4)`],
          correctIndex: 0,
          walkthrough: `Test (5, 5): 2(5) − 5 = 10 − 5 = 5, and 5 ≤ 6 is true, so (5, 5) is a solution. Test (5, −3): 2(5) − (−3) = 10 + 3 = 13, false. Test (4, −4): 2(4) − (−4) = 8 + 4 = 12, false. Test (6, 4): 2(6) − 4 = 12 − 4 = 8, false. Only (5, 5) satisfies the inequality.`,
        },
        mistakes: [
          `Using a solid line for a strict inequality or a dashed line for a non-strict one, mixing up the boundary convention.`,
          `Picking a test point that happens to sit on the boundary line, which never resolves which side to shade.`,
          `Shading based on the original inequality's direction before isolating y, when isolating required dividing by a negative and flipping it.`,
          `Treating the overlap of two shaded regions as the union instead of the intersection when reading a system's graph.`,
          `Forgetting to test both coordinates correctly, substituting x for y or vice versa when checking a point.`,
        ],
      },
    },
    {
      skill: `Linear inequalities in two variables`,
      title: `Linear inequalities in two variables: Systems of Inequalities and Solution Regions`,
      tier: "pro",
      content: {
        summary: `Analyze systems of two or more linear inequalities to identify the shared solution region, its boundary vertices, and which points satisfy every inequality in the system simultaneously.`,
        concepts: [
          `A system of inequalities' solution region is the intersection of every individual inequality's half-plane — a point must satisfy all of them, not just one, to count as a solution.`,
          `The vertices (corner points) of a bounded solution region are found by solving the system of equations formed by each pair of boundary lines that meet at a corner — this is ordinary system-solving applied to the boundary equations.`,
          `A system with two inequalities that have parallel boundary lines either produces an unbounded strip-shaped region (if shaded toward each other) or no solution at all (if shaded away from each other) — check the shading direction of each, not just the lines' slopes.`,
          `If asked "which of these points is NOT a solution to the system," you must check the point against every single inequality — failing even one disqualifies it, even if it satisfies all the others.`,
          `A boundary shared by a solid line in one inequality and a dashed line in another means points exactly on that boundary are only valid if they also satisfy the strict inequality as a strict truth (they generally won't lie in the overall solution set unless also strictly satisfying that one).`,
          `Real-world systems of inequalities often model resource constraints ("no more than 40 hours of labor, at least 10 units of product A") — each constraint becomes one inequality, and the feasible region contains every valid combination of resources.`,
          `The test may ask for the "maximum possible value of [an expression]" over a feasible region — the extreme values of a linear expression over a bounded polygonal region always occur at one of the region's vertices, so you only need to test the corners, not the whole region.`,
          `When translating "at least" and "no more than" constraints for two different variables into a system, keep track of which variable each constraint bounds — swapping them describes an entirely different (and usually empty or nonsensical) region.`,
        ],
        deepDive: [
          `The vertex-testing principle (that a linear expression's max/min over a polygonal feasible region occurs at a corner, never in the interior) is a genuinely deep idea borrowed from linear programming, and the SAT tests a simplified version of it without ever naming it explicitly. Understanding why it's true — a linear expression's level curves are themselves straight lines, so sliding that line across a convex polygon always leaves it last touching a vertex, not an edge's interior or the region's middle — turns what looks like an optimization problem requiring calculus into a simple "evaluate at each corner and compare" checklist.`,
          `A frequent test-writer trap in system-of-inequalities graphing questions is presenting four answer choices as different-looking shaded regions, where three of them differ from the correct one only in whether a boundary is solid/dashed or which side is shaded — the fast, reliable method is always to test one clearly interior point of the claimed region against both original inequalities directly, rather than trying to visually match hand-drawn shading to the mental picture you built.`,
          `Resource-constraint word problems (labor hours, ingredient budgets, staffing minimums) are a direct real-world embodiment of this topic, and they reward writing every constraint down as a separate labeled inequality — including "hidden" constraints like "the number of units produced can't be negative" (x ≥ 0, y ≥ 0), which the test sometimes expects you to infer even though no sentence states it explicitly, because it's implied by the physical meaning of the quantity.`,
          `This topic connects to systems of equations directly: finding a feasible region's vertices is identical to solving 2×2 linear systems — the only new idea is deciding which pairs of boundary lines actually meet at a vertex that's part of the feasible region (as opposed to a pair of lines that intersect somewhere outside the shaded overlap, which is irrelevant to the answer).`,
        ],
        example: {
          prompt: `A feasible region is defined by the system: y ≤ −x + 8, y ≥ 2x − 4, and x ≥ 0. What is the maximum possible value of x + y within this region?`,
          choices: [`6`, `7`, `8`, `9`],
          correctIndex: 2,
          walkthrough: `Find the vertices where pairs of boundaries meet. y = −x + 8 meets y = 2x − 4: −x + 8 = 2x − 4 → 12 = 3x → x = 4, y = 4, giving (4, 4). y = −x + 8 meets x = 0: y = 8, giving (0, 8). y = 2x − 4 meets x = 0: y = −4, giving (0, −4). Evaluate x + y at each vertex: (4, 4) → 8; (0, 8) → 8; (0, −4) → −4. The maximum value of x + y over the feasible region is 8.`,
        },
        mistakes: [
          `Checking a candidate point against only some of the system's inequalities instead of every single one.`,
          `Assuming the maximum of a linear expression over a feasible region occurs somewhere in the interior instead of only at a vertex.`,
          `Forgetting an implied non-negativity constraint (x ≥ 0 or y ≥ 0) that's implied by real-world context but never stated explicitly.`,
          `Solving for an intersection between two boundary lines that don't actually border the shaded feasible region, and mistakenly treating it as a relevant vertex.`,
          `Mixing up which inequality's shading direction applies to which line when two boundaries are parallel.`,
        ],
      },
    },
    {
      skill: `Linear inequalities in two variables`,
      title: `Linear inequalities in two variables: Translating Word Problems into Shaded Regions`,
      tier: "pro",
      content: {
        summary: `Convert descriptive real-world constraints into a two-variable inequality or system, match a word problem to its correct graph, and interpret a shaded region's meaning back in context.`,
        concepts: [
          `Identify the two quantities in the word problem first and assign them explicitly to x and y before writing anything — mixing up which variable represents which quantity is the most common setup error.`,
          `A total-with-two-priced-items constraint ("wants to spend no more than $50 on x apples at $2 each and y oranges at $3 each") becomes 2x + 3y ≤ 50 directly, mirroring the standard-form structure from linear equations.`,
          `Minimum-quantity constraints ("must buy at least 5 items total") add a second inequality, x + y ≥ 5, that must be graphed and satisfied alongside the budget constraint.`,
          `When matching a word problem to one of several candidate graphs, check the intercepts of the boundary lines first (they usually correspond to simple, checkable real-world quantities, like "all budget spent on one item") before worrying about the shading.`,
          `A graph's shaded region represents every combination of the two quantities that satisfies all stated constraints simultaneously — a specific labeled point inside the region should make physical sense when checked against the original word problem, not just the abstract inequality.`,
          `Quantities that can't be negative in real life (number of items purchased, hours worked, distance traveled) restrict the graph to the first quadrant even if the problem never explicitly says x ≥ 0 and y ≥ 0 — build this into your candidate region.`,
          `If a problem describes a strict cap ("cannot exceed") versus an inclusive cap ("up to and including"), that determines whether the boundary line is dashed or solid on the correct graph — read the wording precisely.`,
          `When the question asks to identify a specific point's meaning in context (e.g., "what does the point (10, 5) represent"), translate each coordinate back into its real-world unit and quantity rather than treating it as an abstract ordered pair.`,
        ],
        deepDive: [
          `Word-problem-to-graph matching questions test translation fluency more than graphing mechanics, and the fastest strategy is often to compute each boundary line's intercepts from the word problem directly (e.g., "if all $50 were spent on oranges, how many could be bought?" gives the y-intercept immediately) and match those specific numeric values to the candidate graphs, rather than trying to visually estimate slopes and shading from a mental image.`,
          `A recurring test-writer trap is a problem that describes constraints using "and" language for the real-world scenario but where students accidentally write only one of the two required inequalities, forgetting that "at least 5 total items, without exceeding a $50 budget" needs both x + y ≥ 5 and 2x + 3y ≤ 50 graphed as a system — a single inequality alone answers a different (and easier) question than the one asked.`,
          `The implicit first-quadrant restriction (x ≥ 0, y ≥ 0) is a frequent point of failure specifically on graph-matching questions, where two candidate graphs are algebraically identical inequalities but differ in whether they've been restricted to the physically meaningful quadrant — a purely algebraic check of the inequality alone won't catch this, only reasoning about what the variables represent will.`,
          `Interpreting a labeled point within a shaded region in context connects this skill back to real-world literacy: the test rewards students who can state, in one sentence, what a coordinate pair means (e.g., "10 apples and 5 oranges, which is a combination the customer could actually afford while meeting the minimum item requirement") rather than just confirming it satisfies the inequalities symbolically — some questions specifically ask which statement correctly interprets a point, testing this narrative translation skill directly.`,
        ],
        example: {
          prompt: `A caterer is preparing trays of appetizers. Each meat tray takes 20 minutes to prepare and each vegetable tray takes 15 minutes. The caterer has at most 300 minutes available and must prepare at least 12 trays total. If m is the number of meat trays and v is the number of vegetable trays, which system represents the constraints?`,
          choices: [
            `20m + 15v ≤ 300 and m + v ≥ 12`,
            `20m + 15v ≥ 300 and m + v ≤ 12`,
            `15m + 20v ≤ 300 and m + v ≥ 12`,
            `20m + 15v ≤ 300 and m + v ≤ 12`,
          ],
          correctIndex: 0,
          walkthrough: `Total time used is 20 minutes per meat tray plus 15 minutes per vegetable tray, capped at 300 minutes available: 20m + 15v ≤ 300. The total number of trays must be at least 12: m + v ≥ 12. This matches 20m + 15v ≤ 300 and m + v ≥ 12.`,
        },
        mistakes: [
          `Swapping the per-unit time coefficients between meat and vegetable trays, attaching each rate to the wrong variable.`,
          `Writing the time constraint as ≥ instead of ≤ (or vice versa), reversing "at most" available minutes.`,
          `Writing the minimum-trays constraint as ≤ instead of ≥, reversing "at least."`,
          `Forgetting to include the implicit non-negativity of tray counts when identifying the full feasible region on a graph.`,
          `Selecting a graph or system that satisfies only one of the two stated constraints instead of both simultaneously.`,
        ],
      },
    },

    // ───────────────────────── Systems of two linear equations ─────────────────────────
    {
      skill: `Systems of two linear equations`,
      title: `Systems of two linear equations`,
      tier: "free",
      content: {
        summary: `Solve two equations with two unknowns using substitution or elimination — recognizing which method is faster saves real time.`,
        concepts: [
          `Elimination works best when one variable's coefficients are equal or opposite (or can be made so by multiplying one equation) — add or subtract to cancel it.`,
          `Substitution works best when one equation is already solved for a variable (or easily can be), like y = 2x + 3.`,
          `After finding one variable, plug it back into either original equation (not a modified one) to find the other, and check both.`,
          `A system with no solution has parallel lines (equal slopes, different intercepts); infinite solutions means the two equations describe the same line.`,
          `Before choosing a method, scan both equations for a variable with a coefficient of 1 or −1 — that's usually the fastest signal to use substitution.`,
          `The solution to a system is the single point (x, y) where both equations are simultaneously true — graphically, that's exactly where the two lines cross.`,
        ],
        example: {
          prompt: `If 3x + 2y = 16 and x − 2y = 4, what is the value of x?`,
          choices: [`5`, `4`, `6`, `2`],
          correctIndex: 0,
          walkthrough: `Adding the two equations cancels y: (3x + 2y) + (x − 2y) = 16 + 4 → 4x = 20 → x = 5.`,
        },
        mistakes: [
          `Subtracting instead of adding when coefficients are already opposite, flipping a sign.`,
          `Solving for the wrong variable and answering with y instead of the x the question asked for.`,
          `Substituting into a partially-simplified equation instead of an original one, propagating an earlier arithmetic slip.`,
          `Multiplying only one term of an equation by a constant instead of every term, when preparing to eliminate a variable.`,
          `Forgetting to check the solution in both original equations, missing an error that satisfies only one.`,
        ],
      },
    },
    {
      skill: `Systems of two linear equations`,
      title: `Systems of two linear equations: No-Solution and Infinite-Solution Systems`,
      tier: "pro",
      content: {
        summary: `Solve two equations with two unknowns using substitution or elimination, recognize when a system has no solution or infinitely many, and use coefficient comparison to answer parameter-based questions quickly.`,
        concepts: [
          `Elimination works best when one variable's coefficients are equal or opposite (or can be made so by multiplying one equation) — add or subtract to cancel it.`,
          `Substitution works best when one equation is already solved for a variable (or easily can be), like y = 2x + 3.`,
          `After finding one variable, plug it back into either original equation (not a modified one) to find the other, and check both.`,
          `A system with no solution has parallel lines (equal slopes, different intercepts); infinite solutions means the two equations describe the same line.`,
          `For a system in standard form (Ax + By = C and A'x + B'y = C'), infinite solutions require A/A' = B/B' = C/C' (all three ratios equal); no solution requires A/A' = B/B' but C/C' different.`,
          `A "for what value of k" question about a system's solution count is asking you to compare coefficient ratios, not to solve the system for x and y — solving is the wrong tool entirely for this question type.`,
          `If a system is presented with one equation already in y = mx + b form, convert the other equation to the same form first — comparing slopes and intercepts directly is faster than juggling standard-form ratios.`,
          `Two equations that are scalar multiples of each other (every term multiplied by the same constant) always represent the same line, regardless of how different they look on the page.`,
        ],
        deepDive: [
          `Coefficient-ratio comparison for solution-count questions exists because directly solving a system with a parameter often leads to a dead end (dividing by zero or an expression that could be zero) precisely at the boundary case the question is asking about — recognizing this in advance and switching to ratio comparison avoids an algebraic trap the test sets deliberately.`,
          `The equivalence between "system has infinitely many solutions" and "the two equations describe the same line" is worth internalizing geometrically: since a line is uniquely determined by its slope and one point, two equations produce the same line exactly when they'd graph identically — which is precisely when every coefficient (and the constant) scales by the same factor between the two equations.`,
          `A common test-writer setup gives a system where one equation contains a parameter in a coefficient, like kx + 6y = 12 and 2x + 4y = 8, and asks for the k that makes the system inconsistent (no solution). The ratio test gives k/2 = 6/4 for a parallel (same-slope) system, so k = 3; then check the constant ratio 12/8 = 1.5, which doesn't equal 6/4 = 1.5 — wait, they're equal here, meaning k = 3 actually gives infinite solutions, not no solution. This illustrates why you must check both the coefficient ratio AND the constant ratio before concluding which case applies — assuming "parallel slope" automatically means "no solution" without checking the constant is a frequent, costly error.`,
          `This topic also feeds directly into the two-variable inequality and linear-equation-in-two-variables topics: identical-line questions, parallel-line questions, and infinite-solution-system questions are the same underlying coefficient-matching skill tested through three different vocabularies, so mastering the ratio technique here pays off across multiple question types on the same test.`,
        ],
        example: {
          prompt: `For what value of k does the system 4x + ky = 20 and 8x + 10y = 40 have infinitely many solutions?`,
          choices: [`3`, `4`, `5`, `10`],
          correctIndex: 2,
          walkthrough: `For infinite solutions, all corresponding ratios must be equal: 4/8 = k/10 = 20/40. Since 4/8 = 1/2 and 20/40 = 1/2, both match, confirming this is the infinite-solution case for the right k. Solve k/10 = 1/2 → k = 5.`,
        },
        mistakes: [
          `Trying to solve the system numerically for x and y instead of comparing coefficient ratios when a parameter is involved.`,
          `Checking only the variable-coefficient ratio and concluding "no solution" without also checking whether the constant ratio matches (which would actually mean infinite solutions).`,
          `Cross-multiplying the coefficient ratios inconsistently, mismatching which equation's coefficients go in the numerator versus denominator.`,
          `Assuming two equations that "look different" can't possibly be the same line, without checking if they're scalar multiples.`,
          `Forgetting to convert both equations to the same form (both standard or both slope-intercept) before comparing them.`,
        ],
      },
    },
    {
      skill: `Systems of two linear equations`,
      title: `Systems of two linear equations: Multi-Step Word Problems`,
      tier: "pro",
      content: {
        summary: `Translate two-quantity real-world scenarios into a system of two equations, choosing variables and relationships carefully before solving with substitution or elimination.`,
        concepts: [
          `Assign variables to the two unknown quantities explicitly first ("let a = number of adult tickets, c = number of child tickets") before writing either equation.`,
          `A total-count sentence ("200 tickets were sold in all") becomes one equation (a + c = 200); a total-value sentence ("ticket sales totaled $1,450") becomes the other (using each ticket's price).`,
          `Mixture problems (combining a percentage-x solution and a percentage-y solution to get a target percentage) need one equation for total volume and a second for total "pure" amount — the same total-count/total-value structure in disguise.`,
          `Work-rate problems (two machines or people working together) often need each entity's individual rate as a variable, with the system built from separate scenarios (e.g., "8 hours together" vs. "5 hours alone") described in the problem.`,
          `Age problems reliably use two equations: one relating the two people's current ages, and a second relating their ages at some other point in time (in the past or future) — translate "in 5 years" or "3 years ago" as +5 or −3 applied to BOTH people's ages.`,
          `After solving, sanity-check both values against the real-world context (ages and counts of tickets should be positive whole numbers; rates should be positive) — a negative or fractional "number of people" signals a setup error.`,
          `If the problem only asks for one of the two variables, still solve the full system — shortcuts that try to isolate one variable without fully using both equations often introduce errors in multi-step word problems.`,
          `Watch for problems that give a ratio or comparative relationship ("twice as many adult tickets were sold as child tickets") instead of a raw count — this becomes a substitution-ready equation like a = 2c.`,
        ],
        deepDive: [
          `Multi-step word problems reward a consistent labeling discipline more than any particular algebraic trick: write both "let" statements first, then find the two full sentences in the problem that each translate into one equation. Problems that seem to "have three conditions" are almost always two independent equations plus a definitional restatement, and separating genuine equations from restatements is the actual skill being tested.`,
          `Mixture problems are a particularly elegant application of systems because they secretly encode a weighted average. If x liters of a 20% acid solution mix with y liters of a 50% acid solution to make 10 liters of a 35% solution, the two equations x + y = 10 and 0.2x + 0.5y = 0.35(10) are really saying "total volume" and "total acid content" separately — recognizing this structure means you can set up any mixture problem (paint, alloys, solutions, even weighted GPA-style problems) using the identical template.`,
          `Work-rate problems are the most algebraically demanding subtype because the natural variables are rates (job per hour), not the more intuitive "time to complete a job." A useful reframe: if a pump alone takes h hours to fill a tank, its rate is 1/h tank per hour; combined rates simply add when two entities work simultaneously. Setting up the system in terms of 1/h1 and 1/h2 (rather than h1 and h2 directly) usually produces cleaner linear equations, even though it requires an extra reciprocal step at the very end to report the actual time.`,
          `Age problems reward extremely literal translation of time-shift language: "in 5 years" means adding 5 to every person's current age variable, not just one of them — a frequent, costly error is shifting only the age mentioned nearest to the phrase "in 5 years" in the sentence, rather than shifting both people's ages by the same amount since time passes equally for everyone in the scenario.`,
        ],
        example: {
          prompt: `A 12-liter mixture is created by combining a solution that is 10% saline with a solution that is 40% saline, resulting in a mixture that is 25% saline. How many liters of the 40% saline solution were used?`,
          choices: [`4`, `5`, `6`, `8`],
          correctIndex: 2,
          walkthrough: `Let x = liters of 10% solution, y = liters of 40% solution. Total volume: x + y = 12. Total saline: 0.10x + 0.40y = 0.25(12) = 3. From the first equation, x = 12 − y. Substitute: 0.10(12 − y) + 0.40y = 3 → 1.2 − 0.10y + 0.40y = 3 → 1.2 + 0.30y = 3 → 0.30y = 1.8 → y = 6.`,
        },
        mistakes: [
          `Setting up the "total value" equation using raw quantities instead of weighting each by its price, percentage, or rate.`,
          `Shifting only one person's age when translating a "years ago" or "years from now" phrase, instead of shifting both.`,
          `Confusing total volume with total concentration in a mixture problem, using the wrong total on the right-hand side of an equation.`,
          `Solving only one equation and treating its solution as final, without using the second equation to find (or confirm) the other variable.`,
          `Reporting a rate (like 1/h) as if it were the final answer, forgetting to take the reciprocal to get back to a time.`,
        ],
      },
    },

    // ───────────────────────── Word problems ─────────────────────────
    {
      skill: `Word problems`,
      title: `Word problems`,
      tier: "free",
      content: {
        summary: `Translate multi-step real-world scenarios into linear equations, inequalities, or systems by carefully identifying each unknown and each stated relationship before doing any algebra.`,
        concepts: [
          `Start every word problem by writing an explicit "let" statement for each unknown quantity — vague variables lead to vague (and wrong) equations.`,
          `Read the problem twice: once for the general scenario, once specifically hunting for numbers and relationship words ("more than," "less than," "times," "per," "total").`,
          `A rate word ("per hour," "for each," "$X per unit") always signals multiplication by the variable it modifies — identify the rate and what it's being multiplied by separately.`,
          `Total/combined phrases ("altogether," "in all," "combined") usually signal an addition equation; comparison phrases ("is 3 more than," "is twice as much as") signal a direct substitution relationship between two variables.`,
          `Once you've translated the problem into an equation, inequality, or system, solve it using the appropriate algebra technique — the translation is usually the hard part, not the solving.`,
          `Always answer the actual question asked, not just the first variable you solve for — many word problems solve for an intermediate quantity before the one that's actually requested.`,
          `Check your final answer against the real-world context: negative time, negative counts of people, or a fractional number of discrete items usually signals a setup error, not a valid answer.`,
        ],
        example: {
          prompt: `A parking garage charges $4 for the first hour and $2.50 for each additional hour. If Maria paid $16.50 to park, for how many total hours did she park?`,
          choices: [`5`, `6`, `7`, `8`],
          correctIndex: 1,
          walkthrough: `Let h = total hours parked. The first hour costs $4, and each additional hour (h − 1 of them) costs $2.50: 4 + 2.5(h − 1) = 16.5. Subtract 4: 2.5(h − 1) = 12.5. Divide by 2.5: h − 1 = 5. Add 1: h = 6.`,
        },
        mistakes: [
          `Writing the equation using h instead of (h − 1) for the additional hours, double-counting the first hour's flat rate.`,
          `Solving for an intermediate variable (like "additional hours past the first") and forgetting to add 1 back to get total hours.`,
          `Misreading "for each additional" as applying to every hour instead of only the hours beyond the first.`,
          `Setting up the equation with the flat fee and rate in the wrong roles, swapping which number is added and which is multiplied.`,
          `Rushing to solve before writing a clear "let" statement, leading to an equation that answers a different question than the one asked.`,
        ],
      },
    },
    {
      skill: `Word problems`,
      title: `Word problems: Multi-Step Translation with Rates, Ratios, and Percent Change`,
      tier: "pro",
      content: {
        summary: `Handle word problems that combine several relationships at once — rates, ratios, and percent increase/decrease — by translating each piece into its own algebraic fragment before assembling the full equation.`,
        concepts: [
          `A percent increase of p% multiplies the original quantity by (1 + p/100); a percent decrease multiplies by (1 − p/100) — build this factor before writing the rest of the equation.`,
          `"A is p% more than B" translates to A = B(1 + p/100), NOT A = B + p — a very common conflation between a percent and a raw added amount.`,
          `A ratio statement ("the ratio of adults to children is 3 to 5") introduces a common multiplier k: adults = 3k, children = 5k — this converts a ratio into two clean linear variables in one move.`,
          `Successive percent changes (a price rises 20% then falls 10%) must be applied sequentially to the running total, not added together as +20% − 10% = +10% — the two operations don't commute additively.`,
          `A "combined rate" problem (two people working together, two pipes filling a tank) adds individual rates (amount per unit time), not individual times — translate "time to finish" into "1/time = rate" before combining.`,
          `Multi-step unit conversions embedded in a word problem (feet to miles, minutes to hours, cents to dollars) must be resolved before the main equation is set up, not patched in afterward.`,
          `When a problem describes one quantity in terms of a second, and the second in terms of a third, chain the substitutions in order rather than trying to relate the first and third directly from a partial reading.`,
          `A "what is the original price" question working backward from a final, discounted, tax-included price requires undoing each percent operation in reverse order — divide by the tax factor before dividing by the discount factor if tax was applied after the discount, or vice versa if it wasn't.`,
        ],
        deepDive: [
          `Percent-based word problems are a leading source of otherwise-strong students losing points, because the "same" phrase can encode two different structures depending on subtle wording: "20% of $50" is direct multiplication (0.20 × 50), while "20% more than $50" requires building the multiplier (1.20 × 50) first. Reading past this distinction quickly, rather than pausing to identify which structure applies, is the single biggest source of translation errors in this category.`,
          `Successive percent change problems test whether a student understands that percents apply to a changing base, not a fixed one. A price that increases 20% then decreases 20% does NOT return to its original value — it ends up lower, because the second change (20% of the new, larger amount) is a bigger raw number than the first, but the percentage figure obscures this. Working through the multiplier chain explicitly (1.20 × 0.80 = 0.96, a net 4% decrease) rather than trying to add percentages mentally is the only reliable method.`,
          `Ratio word problems benefit enormously from the "common multiplier k" technique because it converts an abstract proportional relationship into two ordinary linear variables that plug directly into the rest of the problem's equation — for example, if the ratio of two quantities is fixed but their sum or difference is also given, expressing both in terms of k reduces the entire problem to one single-variable linear equation, sidestepping any need for a full system.`,
          `Combined-rate problems reward recognizing that "time to do a job alone" and "rate of doing a job" are reciprocals of each other, and that only rates add sensibly when multiple agents work simultaneously — a frequent, costly error is averaging two given times directly (e.g., claiming two workers who take 4 and 6 hours alone will take 5 hours together), when the correct approach requires adding their rates (1/4 + 1/6) and then reciprocating the sum to find the true combined time.`,
        ],
        example: {
          prompt: `A jacket's price is increased by 25% and then, during a clearance sale, that new price is decreased by 20%. If the final sale price is $60, what was the jacket's original price?`,
          choices: [`$56`, `$60`, `$64`, `$72`],
          correctIndex: 1,
          walkthrough: `Let p = original price. After a 25% increase: 1.25p. After a 20% decrease on that new price: 0.80(1.25p) = 1.00p = p. Setting this equal to the final price: p = 60. So the original price is $60 — the two percent changes exactly offset each other in this case since 1.25 × 0.80 = 1.00.`,
        },
        mistakes: [
          `Adding and subtracting the two percentages directly (25% − 20% = 5% increase) instead of multiplying the sequential factors.`,
          `Applying both percent changes to the original price independently instead of applying the second change to the already-changed price.`,
          `Confusing "25% more than p" with "p + 25" by treating the percent as a flat dollar amount.`,
          `Averaging two workers' individual completion times instead of adding their rates when solving a combined-rate problem.`,
          `Forgetting to convert a ratio statement into a common-multiplier variable, and instead treating the two ratio terms as if they were the actual quantities.`,
        ],
      },
    },
    {
      skill: `Word problems`,
      title: `Word problems: Systems and Inequalities Hidden in Dense Scenarios`,
      tier: "pro",
      content: {
        summary: `Recognize when a wordy, multi-sentence scenario is actually asking for a system of equations, an inequality, or a combination of both, and strip away irrelevant details to reach the necessary structure quickly.`,
        concepts: [
          `A scenario describing two different unknown quantities with two independent relationships between them is a system-of-equations problem, even if the word "system" never appears in the text.`,
          `A scenario asking "what is the minimum/maximum" or using constraint language ("cannot exceed," "must be at least") is an inequality problem, even if it also involves setting up a full equation first.`,
          `Some dense problems require BOTH: build a linear equation or function to model a quantity, then apply an inequality to answer a "what values allow condition X" question about that model.`,
          `Not every number in a dense word problem is relevant to the equation you need — some are used to define context, some define one relationship, and some are pure distractors used to test careful reading; identify which sentence pairs with which unknown before assuming every number belongs in your final equation.`,
          `When a problem gives a scenario across multiple paragraphs, it's often useful to number each sentence and label which unknown(s) and which relationship (equation vs. inequality) it contributes, before writing any algebra.`,
          `A comparison between two people's or two plans' outcomes ("who pays less if...") is typically an inequality question built on top of two linear functions — solve for the equations first, then compare or set up the inequality.`,
          `If a dense problem provides more numeric information than seems necessary, that's often intentional: check whether the "extra" number is actually needed to compute a rate or a total before assuming it's irrelevant.`,
          `Multi-part scenario questions (where an early sentence sets up context used by a later, separate question) require you to carry forward variables and their meanings consistently — redefining a variable partway through a multi-sentence problem is a common self-inflicted error.`,
        ],
        deepDive: [
          `The core difficulty in dense scenario problems isn't the algebra — it's structural recognition: deciding whether the paragraph in front of you wants an equation, an inequality, or a system, since dense SAT word problems deliberately avoid saying "solve this system" or "solve this inequality" outright. A reliable diagnostic: count the unknowns. One unknown quantity usually means an equation or inequality; two unknown quantities usually means a system. Then check for constraint language ("at least," "at most," "cannot exceed," "no more than") layered on top, which signals an inequality is needed either instead of, or in addition to, the equation.`,
          `Distractor numbers are a deliberate test-writing device, not an accident — real standardized exams routinely embed a true but unnecessary fact (like an irrelevant total that isn't needed to answer the specific question asked) specifically to reward students who read for structure rather than grabbing every number they see and plugging it into a formula. The discipline of matching each sentence to a specific variable or relationship before writing algebra is what defeats this device reliably.`,
          `Multi-part dense problems that build on earlier context (a first equation established in paragraph one, reused in a comparison asked in paragraph three) test whether a student can maintain a consistent symbolic model across an extended scenario — this mirrors how real analytical writing and quantitative reasoning work outside of a test, and it rewards writing down your variable definitions explicitly and referring back to them, rather than re-deriving meaning from memory each time a new sentence is read.`,
          `When a scenario combines an equation-building step with an inequality-solving step (build a cost function, then find which values of a variable keep the cost under a budget), the fastest reliable path is to fully resolve the equation/function first, substitute it wholesale into the inequality's constraint, and only then perform the inequality-specific algebra (including sign-flip vigilance) — trying to solve both layers simultaneously in one pass is where multi-step scenario problems most often go wrong.`,
        ],
        example: {
          prompt: `A community center is planning a field trip. Renting a bus costs $250 flat, plus $8 per student for lunch. A separate ticket to the destination costs $12 per student. If the community center has a total budget of $850 for the trip, what is the maximum number of students that can attend?`,
          choices: [`28`, `30`, `32`, `35`],
          correctIndex: 1,
          walkthrough: `Let s = number of students. Total cost = 250 (flat bus fee) + 8s (lunch) + 12s (tickets) = 250 + 20s. This must not exceed the budget: 250 + 20s ≤ 850. Subtract 250: 20s ≤ 600. Divide by 20: s ≤ 30. The maximum number of students is 30.`,
        },
        mistakes: [
          `Treating the flat bus fee as a per-student cost and multiplying it by s along with the other rates.`,
          `Forgetting to combine the two separate per-student rates (lunch and tickets) into a single coefficient before setting up the inequality.`,
          `Solving the inequality correctly but reporting a rounded-up value, exceeding the actual budget by choosing the next whole number above the true boundary.`,
          `Setting up the problem as an equation (looking for an exact budget match) instead of recognizing the "maximum that fits within budget" language as an inequality.`,
          `Losing track of which number in the dense paragraph was the flat fee versus which were the two separate per-student rates.`,
        ],
      },
    },
  ],
});
